force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Case Queue Assignment</label>
</CustomObject>

force-app/main/default/objects/Order_Cost_Center_Setup__c/Order_Cost_Center_Setup__c.object-meta.xml
<CustomObject>
    <description>This object will be used for order cost setup rules which will be used for populating the value and approver on order</description>
    <label>Order Cost Center Setup</label>
    <nameField>
        <displayFormat>OCCS-{00000000}</displayFormat>
        <label>Order Cost Center Setup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Cost Center Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cost_Center_Logic_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_1_Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approver_1_Max_Amount__c</fullName>
    <label>Approver 1 Max Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_1_Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approver_1_Min_Amount__c</fullName>
    <label>Approver 1 Min Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cost_Center_Logic_Tables1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_2_Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approver_2_Max_Amount__c</fullName>
    <label>Approver 2 Max Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_2_Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approver_2_Min_Amount__c</fullName>
    <label>Approver 2 Min Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_3__c.field-meta.xml
<CustomField>
    <fullName>Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cost_Center_Logic_Tables2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_3_Max_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approver_3_Max_Amount__c</fullName>
    <label>Approver 3 Max Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Approver_3_Min_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approver_3_Min_Amount__c</fullName>
    <label>Approver 3 Min Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Call_Center__c.field-meta.xml
<CustomField>
    <fullName>Call_Center__c</fullName>
    <label>Call  Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Grohe</fullName>
            </value>
            <value>
                <fullName>ST</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Cost_Center_Sold_to__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center_Sold_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Center/Sold to</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Plant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Cost Center Setup (Cost Center/Sold to)</relationshipLabel>
    <relationshipName>Cost_Center_Logic_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Credit_Card_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Authorization__c</fullName>
    <label>Credit Card Authorization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Customer_Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Material_Number__c</fullName>
    <label>Customer Material Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>91</fullName>
            </value>
            <value>
                <fullName>96</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID__c</fullName>
    <label>Merchant ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Order_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Record_Type__c</fullName>
    <label>Order Record  Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warranty Order</fullName>
            </value>
            <value>
                <fullName>Credit Card Sales</fullName>
            </value>
            <value>
                <fullName>Good Will</fullName>
            </value>
            <value>
                <fullName>Credit_Card_Sales</fullName>
            </value>
            <value>
                <fullName>Good_Will_Order</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Warranty_Replacement_Order</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Order_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Sub_Type__c</fullName>
    <label>Order Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FD</fullName>
            </value>
            <value>
                <fullName>ZCRS</fullName>
            </value>
            <value>
                <fullName>DR</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>ZWCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A/S Acrylics-860060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Chinaware-840060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Fittings-820060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Furnitures-870060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Metals-850060-ZWCR</fullName>
            </value>
            <value>
                <fullName>Alberta-19994058-ZCRS</fullName>
            </value>
            <value>
                <fullName>British Columbia-19994059-ZCRS</fullName>
            </value>
            <value>
                <fullName>Credit Card-97444000-ZCRS</fullName>
            </value>
            <value>
                <fullName>Credit Memo-974440000-CR</fullName>
            </value>
            <value>
                <fullName>DTC Warranty-380300-FD</fullName>
            </value>
            <value>
                <fullName>DXV Acrylics-950060-ZWCR</fullName>
            </value>
            <value>
                <fullName>DXV Chinaware-930060-ZWCR</fullName>
            </value>
            <value>
                <fullName>DXV Fittings-940060-ZWCR</fullName>
            </value>
            <value>
                <fullName>FG 1 to 5 years-220209-ZWCR</fullName>
            </value>
            <value>
                <fullName>FG 6 to 10 years-220210-FD</fullName>
            </value>
            <value>
                <fullName>Good Will-220211-FD</fullName>
            </value>
            <value>
                <fullName>Grohe-890060-ZWCR</fullName>
            </value>
            <value>
                <fullName>Manitoba-19994056-ZCRS</fullName>
            </value>
            <value>
                <fullName>New Brunswick-19994052-ZCRS</fullName>
            </value>
            <value>
                <fullName>Newfoundland-19994055-ZCRS</fullName>
            </value>
            <value>
                <fullName>Non-Grohe-400211-FD</fullName>
            </value>
            <value>
                <fullName>Nova Scotia-19994053-ZCRS</fullName>
            </value>
            <value>
                <fullName>Nunavut-19994061-ZCRS</fullName>
            </value>
            <value>
                <fullName>Ontario-19994050-ZCRS</fullName>
            </value>
            <value>
                <fullName>Parts in SAP-974440000-ZCRS</fullName>
            </value>
            <value>
                <fullName>Parts in SAP-978880000-ZCRS</fullName>
            </value>
            <value>
                <fullName>Parts not in SAP-974440000-DR</fullName>
            </value>
            <value>
                <fullName>Parts not in SAP-978880000-DR</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island-19994054-ZCRS</fullName>
            </value>
            <value>
                <fullName>Quebec-19994051-ZCRS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F13</fullName>
            </value>
            <value>
                <fullName>F08</fullName>
            </value>
            <value>
                <fullName>C11</fullName>
            </value>
            <value>
                <fullName>C13</fullName>
            </value>
            <value>
                <fullName>C23</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1001</fullName>
            </value>
            <value>
                <fullName>1101</fullName>
            </value>
            <value>
                <fullName>3001</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Ship_to__c.field-meta.xml
<CustomField>
    <fullName>Ship_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship-to</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Plant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Cost Center Setup (Ship-to)</relationshipLabel>
    <relationshipName>Cost_Center_Logic_Tables1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/ZZASBOI2__c.field-meta.xml
<CustomField>
    <fullName>ZZASBOI2__c</fullName>
    <label>ZZASBOI2</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderTrgHandler.cls
/*-------------------------------------------------------------------------------------------------
Author:             
Date:               
Version:            1.0
Description:        Order Trigger Handler
----------------------------------------------------------------------------------------------------*/
/************************MODIFICATION HISTORY*************************************

***********************************************************************************/

public class OrderTrgHandler {
    public void onBeforeInsert(List<Order> newObjects, Map<Id, Order> newMap){  
        List<Order> ListOrderToUpdate = new List<Order>();
        List<Order> ListOoderToPopulatePONumber = new List<Order>();
        
        Set<String> SetRecordTypeName = new Set<String>();
        Set<String> SetOrderType = new Set<String>();
        Set<String> SetOwner = new Set<String>();
        for(Order OrderObj : newObjects ){
            if( OrderObj.Order_Type__c != null && OrderObj.Record_Type_Developer_Name__c != null){
                
                OrderObj.Expected_Delivery_Date__c = Date.Today();
                
                ListOrderToUpdate.add(OrderObj);
                SetRecordTypeName.add(OrderObj.Record_Type_Developer_Name__c);
                SetOrderType.add(OrderObj.Order_Type__c);
                SetOwner.add(OrderObj.OwnerId);
            }
            
            if( String.isNotBlank(OrderObj.Case__c) && String.isBlank(OrderObj.PoNumber)){
                ListOoderToPopulatePONumber.add( OrderObj );
            }
        }
        
        if( ListOrderToUpdate.size() > 0 ){
            PopulateOrderDefault(ListOrderToUpdate, SetRecordTypeName, SetOrderType,SetOwner);
        }
        
        if( ListOoderToPopulatePONumber.size() > 0 ){
            PopulatePONumber( ListOoderToPopulatePONumber );
        }
    }

    public void onAfterInsert(List<Order> newObjects){
        //Get QuoteIds from inserted orders
        List<string> quoteIds = new List<string>();
        for(Order order : newObjects){
            quoteIds.add(order.QuoteId);
        }
        
        List<Id> quotes = new List<Id>(new Map<Id, Quote>([SELECT Id FROM Quote WHERE Id IN:quoteIds AND Active_Quote__c=true]).keySet());
        
        if(quotes.size() > 0){
            List<Opportunity> opportunities = [SELECT Id, StageName FROM Opportunity WHERE FinalQuote__c IN:quotes];
            for(Opportunity opp : opportunities){
                opp.StageName = 'Closed Won';
            }
            update opportunities;
    System.debug('In Order Trigger After Insert');
    System.debug(opportunities);
        }

    }
    
    public void onBeforeUpdate(List<Order> oldObjects, List<Order> newObjects, Map<Id, Order> oldMap, Map<Id, Order> newMap){   
        
        List<Order> ListOrderToUpdate = new List<Order>();
        List<Order> ListOoderToPopulatePONumber = new List<Order>();
        
        Set<String> SetRecordTypeName = new Set<String>();
        Set<String> SetOrderType = new Set<String>();
        Set<String> SetOwner = new Set<String>();
        
        Order OlderOrderObj;
        for(Order OrderObj : newObjects ){
            OlderOrderObj = oldMap.get( OrderObj.Id );
            if( OrderObj.Order_Type__c != null && OrderObj.Record_Type_Developer_Name__c != null && OrderObj.Net_Amount__c != null && (
                OrderObj.Order_Type__c != OlderOrderObj.Order_Type__c || 
                OrderObj.isOrderAmountApproved__c==False||
                OrderObj.Standard_Cost__c != OlderOrderObj.Standard_Cost__c || // Add by hanif to run if Custom Order Amount field changed.
                OrderObj.Record_Type_Developer_Name__c != OlderOrderObj.Record_Type_Developer_Name__c ||
                OrderObj.Net_Amount__c != OlderOrderObj.Net_Amount__c ) ){
                    
                    ListOrderToUpdate.add(OrderObj);
                    SetRecordTypeName.add(OrderObj.Record_Type_Developer_Name__c);
                    SetOrderType.add(OrderObj.Order_Type__c);
                    SetOwner.add(OrderObj.OwnerId);
                }
            
            if( String.isNotBlank(OrderObj.Case__c) && String.isBlank(OrderObj.PoNumber) &&
               ( OrderObj.Case__c != OlderOrderObj.Case__c || OrderObj.CaseContactLastName__c != OlderOrderObj.CaseContactLastName__c || 
                OrderObj.CaseContactFirstName__c != OlderOrderObj.CaseContactFirstName__c || OrderObj.CaseNumber__c != OlderOrderObj.CaseNumber__c ) ){
                    
                    ListOoderToPopulatePONumber.add( OrderObj );
                }
        }
        
        if( ListOrderToUpdate.size() > 0 ){
            PopulateOrderDefault(ListOrderToUpdate, SetRecordTypeName, SetOrderType,SetOwner);
        }
        
        if( ListOoderToPopulatePONumber.size() > 0 ){
            PopulatePONumber( ListOoderToPopulatePONumber );
        }
    }
    
    private void PopulateOrderDefault(List<Order> paramListOrderToUpdate, Set<String> paramSetRecordTypeName, Set<String> paramSetOrderType,Set<String> paramSetOwner){
        Set<String> UserCallCenter = new Set<String>();
        Set<String> UserCountry = new Set<String>();
        map<string,User> mapOwner = new map<string,User>([SELECT Id,Region__c, Call_Center__C FROM User WHERE Id = :paramSetOwner ]);
        
        for(User UserObj:mapOwner.values())
        {
            if(string.isNotBlank(UserObj.Region__c)){
                UserCountry.add(UserObj.Region__c);
            }
            
            if(string.isNotBlank(UserObj.Call_Center__C)){
                UserCallCenter.add(UserObj.Call_Center__C);
            }
        }
        
        String Key;
        map<string,CurrencyType> mapCurrency = new map<string,CurrencyType>();
        for(CurrencyType rec:[SELECT ISOCode, ConversionRate FROM CurrencyType WHERE IsActive=TRUE])
        {
            mapCurrency.put(rec.ISOCode, rec);
        }
        system.debug(paramSetRecordTypeName);        
        system.debug(paramSetOrderType);        
        system.debug(UserCallCenter);
        system.debug(UserCountry);
        SYSTEM.debug([SELECT Call_Center__c, Country_Code__c, 
                      Order_Record_Type__c, Order_Sub_Type__c, Order_Type__c
                      FROM Order_Cost_Center_Setup__c
                      WHERE Order_Record_Type__c IN : paramSetRecordTypeName
                      AND Order_Type__c IN : paramSetOrderType
                      AND Call_Center__c IN :UserCallCenter
                      AND Country_Code__c IN :UserCountry
                     ]);
        Map<String,Order_Cost_Center_Setup__c> MapOrderCostCenterSetup = new Map<String,Order_Cost_Center_Setup__c>();
        for( Order_Cost_Center_Setup__c OrderCostCenterSetupObj : [	SELECT Id, Approver_1__c, Approver_1_Max_Amount__c, Approver_1_Min_Amount__c,
                                                                   Approver_2__c, Approver_2_Max_Amount__c, Approver_2_Min_Amount__c,
                                                                   Approver_3__c, Approver_3_Max_Amount__c, Approver_3_Min_Amount__c,
                                                                   Call_Center__c, Country_Code__c,  Cost_Center_Sold_to__c, Credit_Card_Authorization__c, 
                                                                   Customer_Material_Number__c, Distribution_Channel__c, Division__c, Order_Record_Type__c, 
                                                                   Order_Sub_Type__c, Order_Type__c, Reason_Code__c, Sales_Organization__c, Ship_to__c,CurrencyISOCode,
                                                                   ZZASBOI2__c,Merchant_ID__c
                                                                   FROM Order_Cost_Center_Setup__c
                                                                   WHERE Order_Record_Type__c IN : paramSetRecordTypeName
                                                                   AND Order_Type__c IN : paramSetOrderType
                                                                   AND Call_Center__c IN :UserCallCenter
                                                                   AND Country_Code__c IN :UserCountry ] )
        {
            Key = OrderCostCenterSetupObj.Call_Center__c+'-'+OrderCostCenterSetupObj.Country_Code__c+'-'+OrderCostCenterSetupObj.Order_Record_Type__c+'-'+OrderCostCenterSetupObj.Order_Type__c;
            MapOrderCostCenterSetup.put( Key.toLowerCase(), OrderCostCenterSetupObj );
        }
        system.debug(MapOrderCostCenterSetup);
        for( Order OrderObj : paramListOrderToUpdate ){			
            Key = string.valueOf(mapOwner.get(OrderObj.OwnerId).Call_Center__C) +'-'+
                string.valueOf(mapOwner.get(OrderObj.OwnerId).Region__c) +'-'+
                OrderObj.Record_Type_Developer_Name__c+'-'+OrderObj.Order_Type__c;			
            Order_Cost_Center_Setup__c OrderCostCenterSetupObj;
            if( MapOrderCostCenterSetup.get( Key.toLowerCase() ) != null ){
                OrderCostCenterSetupObj = MapOrderCostCenterSetup.get( Key.toLowerCase() );				
                //OrderObj.Sold_to_Party__c =  OrderCostCenterSetupObj.Cost_Center_Sold_to__c;
                OrderObj.AccountId =  OrderCostCenterSetupObj.Cost_Center_Sold_to__c;
                OrderObj.Credit_Card_Authorization__c =  OrderCostCenterSetupObj.Credit_Card_Authorization__c;
                OrderObj.Customer_Material_Number__C =  OrderCostCenterSetupObj.Customer_Material_Number__c;
                OrderObj.Distribution_Channel__c =  OrderCostCenterSetupObj.Distribution_Channel__c;
                OrderObj.Division__c =  OrderCostCenterSetupObj.Division__c;
                OrderObj.Order_Sub_Type__c =  OrderCostCenterSetupObj.Order_Sub_Type__c;
                OrderObj.xReason_Code__c =  OrderCostCenterSetupObj.Reason_Code__c;
                OrderObj.Sales_Organization__c =  OrderCostCenterSetupObj.Sales_Organization__c;
                OrderObj.Ship_to_Party__c =  OrderCostCenterSetupObj.Ship_to__c;
                OrderObj.Approver__c  = null;
                OrderObj.Merchant_ID__c = OrderCostCenterSetupObj.Merchant_ID__c;
                OrderObj.ZZASBOI2__c = OrderCostCenterSetupObj.ZZASBOI2__c;
                Double conversionRate = 1;
                if (
                    OrderCostCenterSetupObj.CurrencyISOCode != OrderObj.CurrencyISOCode &&
                    mapCurrency.containsKey(OrderObj.CurrencyISOCode)){
                        conversionRate = Double.valueOf(mapCurrency.get(OrderObj.CurrencyISOCode).ConversionRate);
                    }
                
                if( OrderCostCenterSetupObj.Approver_1_Min_Amount__c != null && OrderCostCenterSetupObj.Approver_1_Max_Amount__c != null && 
                   OrderObj.Standard_Cost__c<(OrderCostCenterSetupObj.Approver_1_Min_Amount__c/conversionRate)){
                       OrderObj.isOrderAmountApproved__c = OrderObj.isOrder_Simulator__c;
                   }
                else if( OrderCostCenterSetupObj.Approver_1_Min_Amount__c != null && OrderCostCenterSetupObj.Approver_1_Max_Amount__c != null && 
                        (OrderCostCenterSetupObj.Approver_1_Min_Amount__c/conversionRate) <= OrderObj.Standard_Cost__c && OrderObj.Standard_Cost__c < (OrderCostCenterSetupObj.Approver_1_Max_Amount__c/conversionRate) ){
                            OrderObj.isOrderAmountApproved__c = False;
                            OrderObj.Approver__c = OrderCostCenterSetupObj.Approver_1__c;
                            
                        }else if( OrderCostCenterSetupObj.Approver_2_Min_Amount__c != null && OrderCostCenterSetupObj.Approver_2_Max_Amount__c != null && 
                                 (OrderCostCenterSetupObj.Approver_2_Min_Amount__c/conversionRate) <= OrderObj.Standard_Cost__c && OrderObj.Standard_Cost__c < (OrderCostCenterSetupObj.Approver_2_Max_Amount__c/conversionRate) ){
                                     OrderObj.isOrderAmountApproved__c = False;
                                     OrderObj.Approver__c = OrderCostCenterSetupObj.Approver_2__c;
                                     
                                 }else if( OrderCostCenterSetupObj.Approver_3_Min_Amount__c != null && OrderCostCenterSetupObj.Approver_3_Max_Amount__c != null && 
                                          (OrderCostCenterSetupObj.Approver_3_Min_Amount__c/conversionRate) <= OrderObj.Standard_Cost__c && OrderObj.Standard_Cost__c < (OrderCostCenterSetupObj.Approver_3_Max_Amount__c/conversionRate) ){
                                              OrderObj.isOrderAmountApproved__c = False;
                                              OrderObj.Approver__c = OrderCostCenterSetupObj.Approver_3__c;
                                          } 
            }
        }
    }
    
    private void PopulatePONumber( List<Order> paramListOoderToPopulatePONumber ){
        map<string, Order> mapOrders = new map<string, Order>();
        for( Order OrderObj : paramListOoderToPopulatePONumber )
        {
            Integer CaseNumber = Integer.valueOf(OrderObj.CaseNumber__c);
            String PONumber = String.valueOf(CaseNumber) +'-'+OrderObj.CaseContactLastName__c+'-'+OrderObj.CaseContactFirstName__c;
            OrderObj.PoNumber = PONumber; 
            mapOrders.put(OrderObj.Case__c,OrderObj);
        }
        
        if( !mapOrders.isEmpty()  ){
            List<Order> lstOrder = [Select Id, Name, PoNumber,OrderNumber,Case__c,Case__r.CaseNumber from Order where Case__c in :mapOrders.KeySet()];
        
        map<string,order> existingPO = new map<string,order>();
        for(Order Element:lstOrder){
            existingPO.put(Element.Case__c,Element);
        }
        
        for(String Key:mapOrders.KeySet()){
            if(existingPO.containsKey(Key)){
                Order anOrder = mapOrders.get(Key);
                Order existingOrder =  existingPO.get(Key);
                
                anOrder.addError('There is already order '+existingOrder.OrderNumber+' against case '+existingOrder.Case__r.CaseNumber+'. Only one order per case is permitted.');
            }
        }
        }
        
        
    }
}