force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture project opportunities.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Standard</fullName>
            </value>
            <value>
                <fullName>DXV</fullName>
            </value>
            <value>
                <fullName>Grohe</fullName>
            </value>
            <value>
                <fullName>FIAT</fullName>
            </value>
            <value>
                <fullName>Crane</fullName>
            </value>
            <value>
                <fullName>Inax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/First_Level_Approver__c.field-meta.xml
<CustomField>
    <fullName>First_Level_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1st Level Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Second_Level_Approver__c.field-meta.xml
<CustomField>
    <fullName>Second_Level_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Level Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Third_Level_Approver__c.field-meta.xml
<CustomField>
    <fullName>Third_Level_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3rd Level Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <label>Project Team</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Teams</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wholesalers__c/Wholesalers__c.object-meta.xml
<CustomObject>
    <label>Wholesalers</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Wholesaler  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wholesalers__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Wholesalers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BoxIntegrationUtilTest.cls
@isTest
public class BoxIntegrationUtilTest 
{
    @TestSetup static void createTestSetupData()
    {
        Account acct = UtilityTest.createCustomerAccount();
        Project__c prj = UtilityTest.createProject();

        User approver1 = UtilityTest.createUser();
        prj.First_Level_Approver__c = approver1.Id;        
        
        User approver2 = UtilityTest.createUser();
        prj.Second_Level_Approver__c = approver2.Id;
        
        User approver3 = UtilityTest.createUser();
        prj.Third_Level_Approver__c = approver3.Id;        
        
        update prj;
        
        Project_Team__c pt = UtilityTest.createProjectTeam(prj.Id);
        Wholesalers__c ws = UtilityTest.createWholesaler(acct.Id, prj.Id);
        Test.startTest();
        Opportunity opp = UtilityTest.createProjectOpportunity(prj.Id);
		opp.AccountId = acct.Id;
        update opp;
        
        Id spbId = UtilityTest.getStandardPBId();
        Product2 prod = UtilityTest.createAmericanStandardProduct(spbId);
        Quote qot = UtilityTest.createStandardQuote(spbId, acct, opp);
        QuoteLineItem qli = UtilityTest.createQLI(spbId, qot,prod);
        Test.stopTest();  
    }
    
	@isTest static void testMQLI()
    {
        Test.startTest();
        Quote qot = [select Id, RecordTypeId, Final_Quote__c, Opportunity.Account.brand__c from Quote limit 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(qot);
        
        PageReference pageRef = Page.CreateMQPDFVF;
        pageRef.getParameters().put('id', String.valueOf(qot.Id));
        pageRef.getParameters().put('brands', 'American Standard;DXV');
        Test.setCurrentPage(pageRef);
        
        BoxIntegrationUtil biu = new BoxIntegrationUtil(sc);
        //qe.reviewPrice();
        BoxIntegrationUtil.createFolderinBox(qot.Id);

        Test.stopTest();        
    }
    
	@isTest static void testFQLI()
    {
        Test.startTest();
        Quote qot = [select Id, RecordTypeId, Final_Quote__c from Quote limit 1];
        qot.Final_Quote__c = true;
        update qot;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(qot);
        
        PageReference pageRef = Page.CreateFQPDFVF;
        pageRef.getParameters().put('id', String.valueOf(qot.Id));
        pageRef.getParameters().put('brands', 'American Standard;DXV;FIAT');
        Test.setCurrentPage(pageRef);
        
        BoxIntegrationUtil biu = new BoxIntegrationUtil(sc);

        Test.stopTest();        
    }    
    
	@isTest static void testIQLI()
    {
        Test.startTest();
        
        Account acct = [select id from Account limit 1];
        Opportunity opp = [select id from Opportunity limit 1];
        
        Id spbId = Test.getStandardPricebookId();
        
        Quote qot = UtilityTest.createInfluencerQuote(spbId, acct.id, opp);
        
        Product2 prod = [select Id from Product2 limit 1];
        
        QuoteLineItem qli = UtilityTest.createQLI(spbId, qot, prod);
        
        qot.Final_Quote__c = true;
        update qot;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(qot);
        
        PageReference pageRef = Page.CreateIQPDFVF;
        pageRef.getParameters().put('id', String.valueOf(qot.Id));
        pageRef.getParameters().put('brands', 'American Standard;DXV;FIAT');
        Test.setCurrentPage(pageRef);
        
        BoxIntegrationUtil biu = new BoxIntegrationUtil(sc);
		biu.getFQLineItems();
        
        Test.stopTest();        
    }    
}