force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture project opportunities.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Standard</fullName>
            </value>
            <value>
                <fullName>DXV</fullName>
            </value>
            <value>
                <fullName>Grohe</fullName>
            </value>
            <value>
                <fullName>FIAT</fullName>
            </value>
            <value>
                <fullName>Crane</fullName>
            </value>
            <value>
                <fullName>Inax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Type of property on this project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDUCATION</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>GOVERNMENT/MILITARY</fullName>
                <label>Government/Military</label>
            </value>
            <value>
                <fullName>HEALTHCARE</fullName>
                <label>Healthcare</label>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
                <label>Hospitality</label>
            </value>
            <value>
                <fullName>MIXED USE DEV</fullName>
                <label>Mixed Use Dev</label>
            </value>
            <value>
                <fullName>MULTI FAMILY</fullName>
                <label>Multi Family</label>
            </value>
            <value>
                <fullName>OFFICE BUILDING</fullName>
                <label>Office Building</label>
            </value>
            <value>
                <fullName>PRISON</fullName>
                <label>Prison</label>
            </value>
            <value>
                <fullName>RELIGIOUS/CULTURAL FACILITIES</fullName>
                <label>Religious/Cultural Facilities</label>
            </value>
            <value>
                <fullName>RESTAURANT/RETAIL</fullName>
                <label>Restaurant/Retail</label>
            </value>
            <value>
                <fullName>SHIP</fullName>
                <label>Ship</label>
            </value>
            <value>
                <fullName>SINGLE FAMILY</fullName>
                <label>Single Family</label>
            </value>
            <value>
                <fullName>STADIUM/ENTERTAINMENT</fullName>
                <label>Stadium/Entertainment</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Amusement Park</fullName>
                <isActive>false</isActive>
                <label>AMUSEMENT PARK</label>
            </value>
            <value>
                <fullName>Barracks/Army</fullName>
                <isActive>false</isActive>
                <label>BARRACKS/ARMY</label>
            </value>
            <value>
                <fullName>Buss/Comm Build/Comp</fullName>
                <isActive>false</isActive>
                <label>BUSS/COMM BUILD/COMP</label>
            </value>
            <value>
                <fullName>City/Public Sector</fullName>
                <isActive>false</isActive>
                <label>CITY/PUBLIC SECTOR</label>
            </value>
            <value>
                <fullName>Cultural Facilities</fullName>
                <isActive>false</isActive>
                <label>CULTURAL FACILITIES</label>
            </value>
            <value>
                <fullName>Dept Store/Shopping</fullName>
                <isActive>false</isActive>
                <label>DEPT STORE/SHOPPING</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>GOVERNMENT</label>
            </value>
            <value>
                <fullName>Government Building</fullName>
                <isActive>false</isActive>
                <label>GOVERNMENT BUILDING</label>
            </value>
            <value>
                <fullName>Green Buildings</fullName>
                <isActive>false</isActive>
                <label>GREEN BUILDINGS</label>
            </value>
            <value>
                <fullName>HOSPITAL/MEDICAL CARE</fullName>
                <isActive>false</isActive>
                <label>HOSPITAL/MEDICAL CARE</label>
            </value>
            <value>
                <fullName>Hospitals</fullName>
                <isActive>false</isActive>
                <label>HOSPITALS</label>
            </value>
            <value>
                <fullName>Hotel</fullName>
                <isActive>false</isActive>
                <label>HOTEL</label>
            </value>
            <value>
                <fullName>Hospital/Medical Car</fullName>
                <isActive>false</isActive>
                <label>Hospital/Medical Car</label>
            </value>
            <value>
                <fullName>Hotel / Motel</fullName>
                <isActive>false</isActive>
                <label>Hotel / Motel</label>
            </value>
            <value>
                <fullName>Hotel 4/5 Stars</fullName>
                <isActive>false</isActive>
                <label>Hotel 4/5 Stars</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Wholesalers__c/Wholesalers__c.object-meta.xml
<CustomObject>
    <label>Wholesalers</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Wholesaler  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wholesalers__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Wholesalers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wholesalers__c/fields/Wholesaler__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 AND (3 OR 4))</booleanFilter>
        <errorMessage>Value doesn&#39;t exist or record type is not equal to &quot;Customer&quot; or Subtype is not equal to &quot;ShipTo/Dropship&quot; or Parent Account subtype not equal to &quot;Sold To&quot;!</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Ship_To__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Parent.Is_Parent_SoldTo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Parent_SoldTo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Quote</relationshipLabel>
    <relationshipName>Wholesalers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WholesalersTrgTest.cls
@isTest
public class WholesalersTrgTest {
	
    @isTest
    public static void addWholeselerToProject()
    {
    	Project__c p1 = new Project__c(Name='Test Project1', Project_Type__c='Education');
        Project__c p2 = new Project__c(Name='Test Project1', Project_Type__c='Education');
        insert p1;
        insert p2;
        Account acct1 = UtilityTest.createCustomerAccount();            
            acct1.Brand__c = 'American Standard;Grohe;FIAT';
            update acct1;
        Account acct2 = UtilityTest.createCustomerAccount();            
            acct1.Brand__c = 'American Standard;Grohe;FIAT';
            update acct2;
        
        Wholesalers__c wls1 =new Wholesalers__c(Project__c=p1.id,Wholesaler__c=acct1.id);
        Wholesalers__c wls2 =new Wholesalers__c(Project__c=p2.id,Wholesaler__c=acct2.id);
        Test.startTest();
        List<Wholesalers__c> wlss = new List<Wholesalers__c>();
        wlss.add(wls1);
        wlss.add(wls2);
        insert wlss;
        Project__c prj1 = [select brand__c from Project__c where id=:p1.id ];
       // System.assertEquals('Grohe', prj1.Brand__c);
        Project__c prj2 = [select brand__c from Project__c where id=:p2.id ];
        //System.assertEquals('DXV', prj2.Brand__c);
        Test.stopTest(); 
    }
}