force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture project opportunities.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <label>Project Team</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Teams</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectTeamApprover__c/ProjectTeamApprover__c.object-meta.xml
<CustomObject>
    <label>Project Team Approver Setup</label>
    <nameField>
        <displayFormat>PTAN-{000000}</displayFormat>
        <label>Project Team Approvers Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Approvers Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wholesalers__c/Wholesalers__c.object-meta.xml
<CustomObject>
    <label>Wholesalers</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Wholesaler  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wholesalers__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Wholesalers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductDiscontinuationEmailBatchTest.cls
/************************
Author:         Abid Raza
Created Date:   21/Aug/2018 
Purpose:        Test class to cover code coverage of Product Discontinuation batch class.
************************/


@isTest
public class ProductDiscontinuationEmailBatchTest 
{
    //Create Sample Data 
    @TestSetup static void createTestSetupData()
    {
        List<sObject> ls = Test.loadData(ProjectTeamApprover__c.sObjectType, 'TestData_ProjectTeam_Approver'); 
        Id StdPriceBookId = UtilityTest.getStandardPBId();
        Project__c proj = UtilityTest.createProject();
        Project_Team__c projTeamMember1 = UtilityTest.createProjectTeam(proj.Id);
        //Project_Team__c projTeamMember2 = UtilityTest.createProjectTeam(proj.Id);
        Account acc = UtilityTest.createCustomerAccount();
        Wholesalers__c ws1 = UtilityTest.createWholesaler(acc.Id, proj.Id);
        
        
        Opportunity OppProj = UtilityTest.createProjectOpportunity(proj.Id);
        Quote quote1 = UtilityTest.createStandardQuote(StdPriceBookId, acc, OppProj);
        Product2 ASProd = UtilityTest.createAmericanStandardProduct(StdPriceBookId);
        QuoteLineItem qli1 = UtilityTest.createQLI(StdPriceBookId,quote1,ASProd);
        
        Test.startTest();
        Opportunity Opp = UtilityTest.CreateDisplayOpportunity(acc.Id);
        Wholesalers__c ws = UtilityTest.createWholesaler(acc.Id, opp.Project__c);
        
        OpportunityTeamMember OppTeamMember1 = UtilityTest.createOpportunityTeam(Opp.Id);
        //OpportunityTeamMember OppTeamMember2 = UtilityTest.createOpportunityTeam(Opp.Id);        
        
        Quote quote2 = UtilityTest.createStandardQuote(StdPriceBookId, acc, Opp);        
        Product2 GroheProd = UtilityTest.createGroheProduct();        
        QuoteLineItem qli2 = UtilityTest.createQLI(StdPriceBookId,quote2,GroheProd);
        Test.stopTest();
    }
    
    // Test Method check email sending to Project and Account Team about Product Discontinuation.
    @isTest static void testProductDisContinuationEmails()
    {        
        Test.startTest();
        set<Id> SetProductIds = new Set<Id>();
        for(Product2 prod: [Select Id,Name,Discontinue_date__c from Product2 limit 2])
        {
            SetProductIds.add(prod.Id);
        }
        if(SetProductIds.size() > 0)
        {
            Database.executeBatch(new ProductDiscontinuationEmailBatch(SetProductIds));
        }
        Test.stopTest();
        
    }
}