force-app/main/default/objects/Field_Service_Ticket__c/Field_Service_Ticket__c.object-meta.xml
<CustomObject>
    <label>Field Service Ticket</label>
    <nameField>
        <displayFormat>FST-{0000}</displayFormat>
        <label>SF ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Service Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Service_Ticket__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Service_Ticket__c/fields/Negotiated_Labor_Cost__c.field-meta.xml
<CustomField>
    <fullName>Negotiated_Labor_Cost__c</fullName>
    <label>Negotiated Labor Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Field_Service_Ticket__c/recordTypes/FST_US.recordType-meta.xml
<RecordType>
    <fullName>FST_US</fullName>
    <active>true</active>
    <description>FST for US users</description>
    <label>FST US</label>
</RecordType>

force-app/main/default/classes/FSTHandlerTest.cls
@isTest
public class FSTHandlerTest {
    
    @TestSetup static void createTestSetupData()
    {
         String authResponse2 = BoxTestJsonResponseFactory.AUTH_USER_TOKEN;
         Test.setMock(HttpCalloutMock.class, new BoxTestMockCallout(authResponse2, 'OK', 200)); 
        
        Account ac = UtilityTest.CreateAccount('TestAccount', true);
        Contact cc = UtilityTest.CreateContact(ac.id,'Other');
        List<Case> csList2 = new List<Case>();
        csList2 = UtilityTest.CreateMultipleCase(null,
                                                     Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                     1,
                                                     true);
        
        
        Field_Service_Ticket__c fst = UtilityTest.createFieldServiceTicket(cc.id,
                                             Schema.SObjectType.Field_Service_Ticket__c.getRecordTypeInfosByDeveloperName().get('FST_US').getRecordTypeId(),
                                             csList2[0].id,
                                            false
                                            );
        
        fst.Business_Name__c='Test';
        fst.Approved__c=false;
        fst.Negotiated_Labor_Cost__c=500;
        insert fst;
              
    }
    public static  TestMethod void testFst2(){
        
        Field_Service_Ticket__c fst = [select id from Field_Service_Ticket__c limit 1];        
        fst.Approved__c=true;
        Test.startTest();
                 String authResponse2 = BoxTestJsonResponseFactory.AUTH_USER_TOKEN;
         Test.setMock(HttpCalloutMock.class, new BoxTestMockCallout(authResponse2, 'OK', 200)); 
        update fst;
        Test.stopTest();
    }

}