force-app/main/default/objects/Agency_Zip_Code_Assignment__c/Agency_Zip_Code_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a setup object which will be used to assign the agencies contact based on the zip codes</description>
    <label>Agency Zip Code Assignment</label>
    <nameField>
        <label>Agency Zip Code Assignment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies Zip Code Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This picklist will show the region values</description>
    <inlineHelpText>Regions</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <description>This field will be used to store the zip code for the agency assginment</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Zip Codes</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/Industry_Region_Wise_Rep__c.object-meta.xml
<CustomObject>
    <label>Industry/Region Wise Rep</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Industry/Region Wise Rep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry/Region Wise Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Government/Military</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Mixed Use Dev</fullName>
            </value>
            <value>
                <fullName>Multi Family</fullName>
            </value>
            <value>
                <fullName>Office Building</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Religious/Cultural Facilities</fullName>
            </value>
            <value>
                <fullName>Restaurant/Retail</fullName>
            </value>
            <value>
                <fullName>Ship</fullName>
            </value>
            <value>
                <fullName>Single Family</fullName>
            </value>
            <value>
                <fullName>Stadium/Entertainment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Northwest</fullName>
            </value>
            <value>
                <fullName>Southcentral</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
            <value>
                <fullName>MRO</fullName>
            </value>
            <value>
                <fullName>Transfer DC Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Industry_Region_Wise_Reps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTrgHelper.cls
/*
* Created by: Tectonic (Abid Raza) on 11/Feb/19
* Description: This class is used as helper class to Lead trigger.
* Updated by: 
*/

public class LeadTrgHelper 
{
    // Update Region based on Zip Code.
    public void AssignRegionAsPerZipCode(set<string> SetOfZipCodes, set<Lead> SetOfZIPToRegionLeads)
    {
        Map<string,string> MapOfRegionsAsperZipCode = new  Map<string,string>();
        List<Agency_Zip_Code_Assignment__c> ListofAgencyZipCodeAssignemnts = [Select Id,Name,ZipCode__c,Region__c from Agency_Zip_Code_Assignment__c where ZipCode__c in: SetOfZipCodes];
        system.debug('ListofAgencyZipCodeAssignemnts::'+ListofAgencyZipCodeAssignemnts);
        if(ListofAgencyZipCodeAssignemnts.size() > 0)
        {
            for(Agency_Zip_Code_Assignment__c azca: ListofAgencyZipCodeAssignemnts)
            {
                MapOfRegionsAsperZipCode.put(azca.ZipCode__c,azca.Region__c);
            }
            
            for(Lead led: SetOfZIPToRegionLeads)
            {
                led.Region__c = MapOfRegionsAsperZipCode.get(led.PostalCode);
            }
            system.debug('SetOfZIPToRegionLeads::'+SetOfZIPToRegionLeads);
        }
    }
    
     // Create Task based on region to Regional Manager for Contacts source Pardot.
    public void CreateAndAssignTask(set<string> SetOfRegions, set<Lead> SetOfQualifiedLeads)
    {
        system.debug('SetOfRegions::'+SetOfRegions);
        system.debug('SetOfQualifiedLeads::'+SetOfQualifiedLeads);
        List<Industry_Region_Wise_Rep__c> setupObj = new List<Industry_Region_Wise_Rep__c>();
        List<Task> listTask = new List<Task>();
        
        if(SetOfRegions.size()>0)
        {
            setupObj = [Select id,User__c,Industry__c,Region__c From  Industry_Region_Wise_Rep__c where Region__c IN : SetOfRegions];
            system.debug('setup'+setupObj.size());
        }
        if(setupObj.size()>0)
        {
            for (Lead led : SetOfQualifiedLeads)
            {
                for(Industry_Region_Wise_Rep__c sObj: setupObj)
                {
                    if(sObj.Region__c==led.Region__c)
                    {
                        Task tsk =  new Task();
                        tsk.Status = 'Open';
                        tsk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
                        tsk.ActivityDate = System.today().AddMonths(1);
                        if(led.Rating == 'Hot')
                        	tsk.Subject = 'Lead ' + led.FirstName + ' ' + led.LastName +' is hot lead and qualified. Please follow-up.';
                        else
                            tsk.Subject = 'Lead ' + led.FirstName + ' ' + led.LastName +' is qualified. Please follow-up.';
                        tsk.OwnerId = sObj.User__c;
                        tsk.WhoId = led.Id;
                        listTask.add(tsk);
                    }
                }
            }
            
            if(listTask.size() > 0)
            {
                Insert listTask;
                system.debug('listTask'+listTask);
            }
        }
    }
}