force-app/main/default/objects/Agency_Zip_Code_Assignment__c/Agency_Zip_Code_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a setup object which will be used to assign the agencies contact based on the zip codes</description>
    <label>Agency Zip Code Assignment</label>
    <nameField>
        <label>Agency Zip Code Assignment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies Zip Code Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This picklist will show the region values</description>
    <inlineHelpText>Regions</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <description>This field will be used to store the zip code for the agency assginment</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Zip Codes</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/Industry_Region_Wise_Rep__c.object-meta.xml
<CustomObject>
    <label>Industry/Region Wise Rep</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Industry/Region Wise Rep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry/Region Wise Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Northwest</fullName>
            </value>
            <value>
                <fullName>Southcentral</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
            <value>
                <fullName>MRO</fullName>
            </value>
            <value>
                <fullName>Transfer DC Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Industry_Region_Wise_Reps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactTrgTest.cls
@istest
public class ContactTrgTest 
{
    @TestSetup static void createTestSetupData()
    {
        Account acc = UtilityTest.createCustomerAccount();
        Contact con = UtilityTest.CreateContact(acc.Id,'Consumer');
        Agency_Zip_Code_Assignment__c azca = new Agency_Zip_Code_Assignment__c();
        azca.Region__c = 'Northeast';
        azca.ZipCode__c = '08854';
        insert azca;
        Industry_Region_Wise_Rep__c irwr = new Industry_Region_Wise_Rep__c();
        irwr.Region__c = 'Northeast';
        irwr.User__c = Userinfo.getUserId();
        insert irwr;
    }
    
    @isTest static void testUpdateProduct()
    {
        Test.startTest();
            Contact con = [Select Id,Name,Contact_Activity_in_Pardot__c from Contact limit 1];
            con.MailingPostalCode = '08854';
        	con.Contact_Activity_in_Pardot__c = 'Form Filled';
        	Update con;
        	con.Contact_Activity_in_Pardot__c = 'No Activity';
        	Update con;
        	con.Contact_Activity_in_Pardot__c = 'Hot Contact';
        	Update con;
        	con.Unqualified_Prospect_Status__c = '90 Days Prior';
        	Update con;
        	con.Unqualified_Prospect_Status__c = 'Launch Day';
        	Update con;
        Test.stopTest();
    }
	
}