force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture project opportunities.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Project address&#39; city</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&#39;US&#39;</defaultValue>
    <description>Project address&#39; country</description>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/First_Level_Approver__c.field-meta.xml
<CustomField>
    <fullName>First_Level_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1st Level Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Project address&#39; zip/postal code</description>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Region__c.field-meta.xml
<CustomField>
    <fullName>Project_Region__c</fullName>
    <label>Project Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>MRO</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Northwest</fullName>
            </value>
            <value>
                <fullName>Southcentral</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
            <value>
                <fullName>Transfer DC Location</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Type of property on this project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDUCATION</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>GOVERNMENT/MILITARY</fullName>
                <label>Government/Military</label>
            </value>
            <value>
                <fullName>HEALTHCARE</fullName>
                <label>Healthcare</label>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
                <label>Hospitality</label>
            </value>
            <value>
                <fullName>MIXED USE DEV</fullName>
                <label>Mixed Use Dev</label>
            </value>
            <value>
                <fullName>MULTI FAMILY</fullName>
                <label>Multi Family</label>
            </value>
            <value>
                <fullName>OFFICE BUILDING</fullName>
                <label>Office Building</label>
            </value>
            <value>
                <fullName>PRISON</fullName>
                <label>Prison</label>
            </value>
            <value>
                <fullName>RELIGIOUS/CULTURAL FACILITIES</fullName>
                <label>Religious/Cultural Facilities</label>
            </value>
            <value>
                <fullName>RESTAURANT/RETAIL</fullName>
                <label>Restaurant/Retail</label>
            </value>
            <value>
                <fullName>SHIP</fullName>
                <label>Ship</label>
            </value>
            <value>
                <fullName>SINGLE FAMILY</fullName>
                <label>Single Family</label>
            </value>
            <value>
                <fullName>STADIUM/ENTERTAINMENT</fullName>
                <label>Stadium/Entertainment</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Amusement Park</fullName>
                <isActive>false</isActive>
                <label>AMUSEMENT PARK</label>
            </value>
            <value>
                <fullName>Barracks/Army</fullName>
                <isActive>false</isActive>
                <label>BARRACKS/ARMY</label>
            </value>
            <value>
                <fullName>Buss/Comm Build/Comp</fullName>
                <isActive>false</isActive>
                <label>BUSS/COMM BUILD/COMP</label>
            </value>
            <value>
                <fullName>City/Public Sector</fullName>
                <isActive>false</isActive>
                <label>CITY/PUBLIC SECTOR</label>
            </value>
            <value>
                <fullName>Cultural Facilities</fullName>
                <isActive>false</isActive>
                <label>CULTURAL FACILITIES</label>
            </value>
            <value>
                <fullName>Dept Store/Shopping</fullName>
                <isActive>false</isActive>
                <label>DEPT STORE/SHOPPING</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>GOVERNMENT</label>
            </value>
            <value>
                <fullName>Government Building</fullName>
                <isActive>false</isActive>
                <label>GOVERNMENT BUILDING</label>
            </value>
            <value>
                <fullName>Green Buildings</fullName>
                <isActive>false</isActive>
                <label>GREEN BUILDINGS</label>
            </value>
            <value>
                <fullName>HOSPITAL/MEDICAL CARE</fullName>
                <isActive>false</isActive>
                <label>HOSPITAL/MEDICAL CARE</label>
            </value>
            <value>
                <fullName>Hospitals</fullName>
                <isActive>false</isActive>
                <label>HOSPITALS</label>
            </value>
            <value>
                <fullName>Hotel</fullName>
                <isActive>false</isActive>
                <label>HOTEL</label>
            </value>
            <value>
                <fullName>Hospital/Medical Car</fullName>
                <isActive>false</isActive>
                <label>Hospital/Medical Car</label>
            </value>
            <value>
                <fullName>Hotel / Motel</fullName>
                <isActive>false</isActive>
                <label>Hotel / Motel</label>
            </value>
            <value>
                <fullName>Hotel 4/5 Stars</fullName>
                <isActive>false</isActive>
                <label>Hotel 4/5 Stars</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/ReassignProjectTeam__c.field-meta.xml
<CustomField>
    <fullName>ReassignProjectTeam__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field will be used to reassign the Project Team.</description>
    <inlineHelpText>Only Project Team, (Non Approvers) will be reassigned.</inlineHelpText>
    <label>Reassign Project Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Second_Level_Approver__c.field-meta.xml
<CustomField>
    <fullName>Second_Level_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Level Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Project address&#39; state</description>
    <label>State/Province</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Third_Level_Approver__c.field-meta.xml
<CustomField>
    <fullName>Third_Level_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3rd Level Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Project_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Value__c</fullName>
    <description>This is auto populated based on MQ or FQ - this is when quote is approved and send over to Agency and team. Before that Budgetary quote will be generated and will remain in Salesforce to be distributed</description>
    <label>Total Project Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <label>Project Team</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Teams</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wholesalers__c/Wholesalers__c.object-meta.xml
<CustomObject>
    <label>Wholesalers</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Wholesaler  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wholesalers__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Wholesalers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectTrgTest.cls
@isTest
public class ProjectTrgTest 
{
    @isTest static void testCreateProjWithApprovers()
    {
        
        Agency__c agn1 = UtilityTest.CreateAgency();
        UtilityTest.CreateAgencyZipCodeAssignment();
        Account acct = UtilityTest.createCustomerAccount();
        Project__c prj = UtilityTest.createProjectWithApprovers();
        System.debug('KA:: prj owner Test Class'+ prj.id+'-'+prj.OwnerId);
        Project_Team__c pt = UtilityTest.createProjectTeam(prj.Id);
        UtilityTest.CreateProjectTeamSetup();
        UtilityTest.CreateProjectTeamApproverSetup();
        Wholesalers__c ws = UtilityTest.createWholesaler(acct.Id, prj.Id);
        Test.startTest();
        Opportunity opp = UtilityTest.createProjectOpportunity(prj.Id);

        Id spbId = UtilityTest.getStandardPBId();
        Product2 prod = UtilityTest.createAmericanStandardProduct(spbId);
        Quote qot = UtilityTest.createStandardQuote(spbId, acct, opp);
        QuoteLineItem qli = UtilityTest.createQLI(spbId, qot,prod);
        Test.stopTest();
    }
    
    @isTest static void testCreateProjWith2ndApprovers()
    {
        Test.startTest();
        Account acct = UtilityTest.createCustomerAccount();

        User approver2 = UtilityTest.createUser();
       
        Project__c prj = new Project__c();
        prj.Name = 'Test Project';
        prj.Project_Type__c = 'Ship';
        prj.City__c = 'Atlanta';
        prj.State__c = 'GA';
        prj.Postal_Code__c = '30301';
        prj.Country__c = 'US';
        prj.Stage__c = 'Open';
        prj.Project_Region__c = 'Southeast';
        prj.second_Level_Approver__c = approver2.Id;
       
        insert prj;        
        UtilityTest.CreateProjectTeamSetup();
        UtilityTest.CreateProjectTeamApproverSetup();
        Project_Team__c pt = UtilityTest.createProjectTeam(prj.Id);
        Wholesalers__c ws = UtilityTest.createWholesaler(acct.Id, prj.Id);     
        Opportunity opp = UtilityTest.createProjectOpportunity(prj.Id);

        Id spbId = UtilityTest.getStandardPBId();
        Product2 prod = UtilityTest.createAmericanStandardProduct(spbId);
        Quote qot = UtilityTest.createStandardQuote(spbId, acct, opp);
        QuoteLineItem qli = UtilityTest.createQLI(spbId, qot,prod);
        Test.stopTest();
    }  
    
    @isTest static void testCreateProjWith3rdApprovers()
    {
        Test.startTest();
        Account acct = UtilityTest.createCustomerAccount();
        
        User approver3 = UtilityTest.createUser();
       
        Project__c prj = new Project__c();
        prj.Name = 'Test Project';
        prj.Project_Type__c = 'Ship';
        prj.City__c = 'Atlanta';
        prj.State__c = 'GA';
        prj.Postal_Code__c = '30301';
        prj.Country__c = 'US';
        prj.Stage__c = 'Open';
        prj.Project_Region__c = 'Southeast';
        prj.Third_Level_Approver__c = approver3.Id;
       
        insert prj;        
        
        Project_Team__c pt = UtilityTest.createProjectTeam(prj.Id);
        UtilityTest.CreateProjectTeamSetup();
        UtilityTest.CreateProjectTeamApproverSetup();
        Wholesalers__c ws = UtilityTest.createWholesaler(acct.Id, prj.Id);
        Opportunity opp = UtilityTest.createProjectOpportunity(prj.Id);

        Id spbId = UtilityTest.getStandardPBId();
        Product2 prod = UtilityTest.createAmericanStandardProduct(spbId);
        Quote qot = UtilityTest.createStandardQuote(spbId, acct, opp);
        QuoteLineItem qli = UtilityTest.createQLI(spbId, qot,prod);
        Test.stopTest();
    }    
    
    @isTest public static void testUpdateApprover()
    {
        Test.startTest();
        Account acct = UtilityTest.createCustomerAccount();
        Project__c prj = UtilityTest.createProject();

        Project_Team__c pt = UtilityTest.createProjectTeam(prj.Id);
        Wholesalers__c ws = UtilityTest.createWholesaler(acct.Id, prj.Id);
        Opportunity opp = UtilityTest.createProjectOpportunity(prj.Id);

        Id spbId = UtilityTest.getStandardPBId();
        Product2 prod = UtilityTest.createAmericanStandardProduct(spbId);
        //Quote qot = UtilityTest.createStandardQuote(spbId, acct, opp);
        //QuoteLineItem qli = UtilityTest.createQLI(spbId, qot,prod);   
        
        User approver1 = UtilityTest.createUser();
        prj.First_Level_Approver__c = approver1.Id;        
        
        User approver2 = UtilityTest.createUser();
        prj.Second_Level_Approver__c = approver2.Id;
        
        User approver3 = UtilityTest.createUser();
        prj.Third_Level_Approver__c = approver3.Id;        
		User owner1 = UtilityTest.createUser(); 
        prj.OwnerId=owner1.id;
        update prj;
        
        User owner2 = UtilityTest.createUser(); 
        prj.OwnerId=owner2.id;
        update prj;
         
        prj.OwnerId=owner1.id;
        update prj;
         
        //UtilityTest.CreateProjectTeamSetup();
        //UtilityTest.CreateProjectTeamApproverSetup();
        Test.stopTest();
    }


    @IsTest public static void ProjectTrgHandler_TestInsert(){
        Test.startTest();
        UtilityTest.CreateAgencyZipCodeAssignment();
        UtilityTest.CreateProjectTeamSetup();
        UtilityTest.CreateProjectTeamApproverSetup();
        
        
        Project__c ProjectObj = UtilityTest.createProject2();
        
        Test.stopTest();
    }

    @IsTest public static void ProjectTrgHandler_Testupdate(){
        Test.startTest();
        UtilityTest.CreateAgencyZipCodeAssignment();
        UtilityTest.CreateProjectTeamSetup();
        UtilityTest.CreateProjectTeamApproverSetup();
        Project__c ProjectObj = UtilityTest.createProject2();
        
        ProjectObj.Postal_Code__c = null;
        //User us =UtilityTest.createUser();
       // ProjectObj.OwnerId=us.id;
        update ProjectObj;
        
        Test.stopTest();
    }

    @IsTest public static void ProjectTrgHandler_Testupdate2(){
        Test.startTest();
        UtilityTest.CreateAgencyZipCodeAssignment();
        UtilityTest.CreateProjectTeamSetup();
        UtilityTest.CreateProjectTeamApproverSetup();
        Project__c ProjectObj = UtilityTest.createProject2();        
        ProjectObj.Postal_Code__c = '220065';
        ProjectObj.ReassignProjectTeam__c = true;
        ProjectObj.Total_Project_Value__c = 00.00;
        update ProjectObj;        
        Test.stopTest();
    }
}