force-app/main/default/objects/Order_Cost_Center_Setup__c/Order_Cost_Center_Setup__c.object-meta.xml
<CustomObject>
    <description>This object will be used for order cost setup rules which will be used for populating the value and approver on order</description>
    <label>Order Cost Center Setup</label>
    <nameField>
        <displayFormat>OCCS-{00000000}</displayFormat>
        <label>Order Cost Center Setup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Cost Center Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Call_Center__c.field-meta.xml
<CustomField>
    <fullName>Call_Center__c</fullName>
    <label>Call  Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Grohe</fullName>
            </value>
            <value>
                <fullName>ST</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Order_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Sub_Type__c</fullName>
    <label>Order Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FD</fullName>
            </value>
            <value>
                <fullName>ZCRS</fullName>
            </value>
            <value>
                <fullName>DR</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>ZWCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Cost_Center_Setup__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A/S Acrylics-860060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Chinaware-840060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Fittings-820060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Furnitures-870060-ZWCR</fullName>
            </value>
            <value>
                <fullName>A/S Metals-850060-ZWCR</fullName>
            </value>
            <value>
                <fullName>Alberta-19994058-ZCRS</fullName>
            </value>
            <value>
                <fullName>British Columbia-19994059-ZCRS</fullName>
            </value>
            <value>
                <fullName>Credit Card-97444000-ZCRS</fullName>
            </value>
            <value>
                <fullName>Credit Memo-974440000-CR</fullName>
            </value>
            <value>
                <fullName>DTC Warranty-380300-FD</fullName>
            </value>
            <value>
                <fullName>DXV Acrylics-950060-ZWCR</fullName>
            </value>
            <value>
                <fullName>DXV Chinaware-930060-ZWCR</fullName>
            </value>
            <value>
                <fullName>DXV Fittings-940060-ZWCR</fullName>
            </value>
            <value>
                <fullName>FG 1 to 5 years-220209-ZWCR</fullName>
            </value>
            <value>
                <fullName>FG 6 to 10 years-220210-FD</fullName>
            </value>
            <value>
                <fullName>Good Will-220211-FD</fullName>
            </value>
            <value>
                <fullName>Grohe-890060-ZWCR</fullName>
            </value>
            <value>
                <fullName>Manitoba-19994056-ZCRS</fullName>
            </value>
            <value>
                <fullName>New Brunswick-19994052-ZCRS</fullName>
            </value>
            <value>
                <fullName>Newfoundland-19994055-ZCRS</fullName>
            </value>
            <value>
                <fullName>Non-Grohe-400211-FD</fullName>
            </value>
            <value>
                <fullName>Nova Scotia-19994053-ZCRS</fullName>
            </value>
            <value>
                <fullName>Nunavut-19994061-ZCRS</fullName>
            </value>
            <value>
                <fullName>Ontario-19994050-ZCRS</fullName>
            </value>
            <value>
                <fullName>Parts in SAP-974440000-ZCRS</fullName>
            </value>
            <value>
                <fullName>Parts in SAP-978880000-ZCRS</fullName>
            </value>
            <value>
                <fullName>Parts not in SAP-974440000-DR</fullName>
            </value>
            <value>
                <fullName>Parts not in SAP-978880000-DR</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island-19994054-ZCRS</fullName>
            </value>
            <value>
                <fullName>Quebec-19994051-ZCRS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddProductOrderCtrlTest.cls
/************************
Author:         Azfer Pervaiz
Created Date:   08/Aug/2018 
Purpose:        AddProductOrderCtrlTest Test class for the AddProductOrderCtrl.

************************MODIFICATION HISTORY**************************************
Added on             Added By               Description
**********************************************************************************
08/Aug/2018          Azfer Pervaiz          Initial Development 
***********************************************************************************/
@isTest
public class AddProductOrderCtrlTest {
    static Account anAccount = new Account();
    //Create Sample Data 
    @TestSetup static void createTestSetupData(){
        Id StdPriceBookId = UtilityTest.getStandardPBId();
        anAccount = UtilityTest.createCustomerAccount();
        Product2 ASProd = UtilityTest.createAmericanStandardProduct(StdPriceBookId);
        List<sObject> ls = Test.loadData(Order_Cost_Center_Setup__c.sObjectType, 'TestData_OrderLogic'); 
    }
    
    @isTest static void InitCtrlTest() {
        
        Account anAccount = [select id from account limit 1][0];
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
            Product2 prod = UtilityTest.createGroheProduct();
            
            Asset ast = new Asset();
            ast.Name = 'Test Asset';
            ast.Quantity = 1;
            ast.Sub_Channels__c = 'Project';
            ast.AccountId = anAccount.Id;
            ast.Product2Id = prod.Id;
            ast.PurchaseDate = System.Date.today();
            ast.InstallDate =System.Date.today();
            ast.ContactId = con.Id;
            insert ast; 
            
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            insert anOrder;
            
            Test.startTest();
            AddProductOrderCtrl.InitCtrl( anOrder.Id );
            Test.stopTest();
        }
    }
    
    @isTest static void AddProductCtrlTest() {
        
        Account anAccount = [select id from account limit 1][0];
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
            
        Product2 prod = UtilityTest.createGroheProduct();
        
        Asset ast = new Asset();
        ast.Name = 'Test Asset';
        ast.Quantity = 1;
        ast.Sub_Channels__c = 'Project';
        ast.AccountId = anAccount.Id;
        ast.Product2Id = prod.Id;
        ast.PurchaseDate = System.Date.today();
        ast.InstallDate =System.Date.today();
		ast.ContactId = con.Id;            
        insert ast;            
            
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            insert anOrder;
            
            List<AddProductOrderCtrl.OrderItemWrapper> ListOrderItemWrapper = AddProductOrderCtrl.InitCtrl( anOrder.Id );
            String JSONStringListOrderItemWrapper = JSON.serialize( ListOrderItemWrapper );
            
            Test.startTest();
            AddProductOrderCtrl.AddProductCtrl( JSONStringListOrderItemWrapper );
            Test.stopTest();
        }
    }
    
    @isTest static void SaveProductCtrlReturnListTest() {
        
        Account anAccount = [select id from account limit 1][0];
        Product2 Product2Obj = UtilityTest.createGroheProduct();
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
        
        Asset ast = new Asset();
        ast.Name = 'Test Asset';
        ast.Quantity = 1;
        ast.Sub_Channels__c = 'Project';
        ast.AccountId = anAccount.Id;
        ast.Product2Id = Product2Obj.Id;
        ast.PurchaseDate = System.Date.today();
        ast.InstallDate =System.Date.today();
		ast.ContactId = con.Id;            
        insert ast;             
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            insert anOrder;
            List<AddProductOrderCtrl.OrderItemWrapper> ListOrderItemWrapper = AddProductOrderCtrl.InitCtrl( anOrder.Id );
            
            for( AddProductOrderCtrl.OrderItemWrapper OrderItemWrapperObj : ListOrderItemWrapper ){
                OrderItemWrapperObj.ProductCode = Product2Obj.SAP_Product_Code__c;
                OrderItemWrapperObj.ProductQuantity = 10;
                //OrderItemWrapperObj.ProductAlterNumber = 10;
            }
            
            ListOrderItemWrapper[0].ProductCode = 'Test';
            ListOrderItemWrapper[0].ProductQuantity = 0;
            
            String JSONStringListOrderItemWrapper = JSON.serialize( ListOrderItemWrapper );
            
            Test.startTest();
            AddProductOrderCtrl.SaveProductCtrl( anOrder.Id, 'Standard Price Book', JSONStringListOrderItemWrapper );
            Test.stopTest();
        }
    }
    
    @isTest static void SaveProductCtrlReturnListTest2() {
        
        Account anAccount = [select id from account limit 1][0];
        Product2 Product2Obj = UtilityTest.createGroheProduct();
        Product2Obj.Description='d';
        update Product2Obj;
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
            Asset ast = new Asset();
            ast.Name = 'Test Asset';
            ast.Quantity = 1;
            ast.Sub_Channels__c = 'Project';
            ast.AccountId = anAccount.Id;
            ast.Product2Id = Product2Obj.Id;
            ast.PurchaseDate = System.Date.today();
            ast.InstallDate =System.Date.today();
			ast.ContactId = con.Id;            
            insert ast;            
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            anOrder.CurrencyISOCode = 'USD';
            anOrder.Pricebook2Id = null;
            insert anOrder;
            List<AddProductOrderCtrl.OrderItemWrapper> ListOrderItemWrapper = AddProductOrderCtrl.InitCtrl( anOrder.Id );
            
            for( AddProductOrderCtrl.OrderItemWrapper OrderItemWrapperObj : ListOrderItemWrapper ){
                OrderItemWrapperObj.ProductCode = Product2Obj.SAP_Product_Code__c;
                OrderItemWrapperObj.ProductQuantity = 10;
                //OrderItemWrapperObj.ProductAlterNumber = 10;
            }
            
            ListOrderItemWrapper[0].ProductCode = 'Test';
            ListOrderItemWrapper[0].ProductQuantity = 0;
            
            String JSONStringListOrderItemWrapper = JSON.serialize( ListOrderItemWrapper );
            
            Test.startTest();
            AddProductOrderCtrl.SaveProductCtrl( anOrder.Id, 'Standard Price Book', JSONStringListOrderItemWrapper );
            Test.stopTest();
        }
    }
    
    @isTest static void SaveProductCtrlTest() {
        
        Account anAccount = [select id from account limit 1][0];
        Product2 Product2Obj = UtilityTest.createGroheProduct();
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
            Asset ast = new Asset();
            ast.Name = 'Test Asset';
            ast.Quantity = 1;
            ast.Sub_Channels__c = 'Project';
            ast.AccountId = anAccount.Id;
            ast.Product2Id = Product2Obj.Id;
            ast.PurchaseDate = System.Date.today();
            ast.InstallDate =System.Date.today();
			ast.ContactId = con.Id;            
            insert ast;             
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            insert anOrder;
            List<AddProductOrderCtrl.OrderItemWrapper> ListOrderItemWrapper = AddProductOrderCtrl.InitCtrl( anOrder.Id );
            
            for( AddProductOrderCtrl.OrderItemWrapper OrderItemWrapperObj : ListOrderItemWrapper ){
                OrderItemWrapperObj.ProductCode = Product2Obj.SAP_Product_Code__c;
                OrderItemWrapperObj.ProductQuantity = 10;
                //OrderItemWrapperObj.ProductAlterNumber = 10;
            }
            
            String JSONStringListOrderItemWrapper = JSON.serialize( ListOrderItemWrapper );
            
            Test.startTest();
            AddProductOrderCtrl.SaveProductCtrl( anOrder.Id, 'Standard Price book', JSONStringListOrderItemWrapper );
            Test.stopTest();
        }
    }
    
    @isTest static void SaveProductCtrlWithOrderWithOutPBTest() {
        
        Account anAccount = [select id from account limit 1][0];
        Product2 Product2Obj = UtilityTest.createGroheProduct();
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
            Asset ast = new Asset();
            ast.Name = 'Test Asset';
            ast.Quantity = 1;
            ast.Sub_Channels__c = 'Project';
            ast.AccountId = anAccount.Id;
            ast.Product2Id = Product2Obj.Id;
            ast.PurchaseDate = System.Date.today();
            ast.InstallDate =System.Date.today();
            ast.ContactId = con.Id; 
            insert ast;             
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            insert anOrder;
            
            List<AddProductOrderCtrl.OrderItemWrapper> ListOrderItemWrapper = AddProductOrderCtrl.InitCtrl( anOrder.Id );
            
            for( AddProductOrderCtrl.OrderItemWrapper OrderItemWrapperObj : ListOrderItemWrapper ){
                OrderItemWrapperObj.ProductCode = Product2Obj.SAP_Product_Code__c;
                OrderItemWrapperObj.ProductQuantity = 10;
                // OrderItemWrapperObj.ProductAlterNumber = 10;
            }
            
            String JSONStringListOrderItemWrapper = JSON.serialize( ListOrderItemWrapper );
            
            Test.startTest();
            AddProductOrderCtrl.SaveProductCtrl( anOrder.Id, 'Standard Price Book', JSONStringListOrderItemWrapper );
            Test.stopTest();
        }
    }
    
    
    
    @isTest static void CheckPastedDateCtrlTest() {
        
        Account anAccount = [select id from account limit 1][0];
        Product2 Product2Obj = UtilityTest.createGroheProduct();
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
            Asset ast = new Asset();
            ast.Name = 'Test Asset';
            ast.Quantity = 1;
            ast.Sub_Channels__c = 'Project';
            ast.AccountId = anAccount.Id;
            ast.Product2Id = Product2Obj.Id;
            ast.PurchaseDate = System.Date.today();
            ast.InstallDate =System.Date.today();
            ast.ContactId = con.Id; 
            insert ast;             
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            insert anOrder;
            String StringTableData = '<tr><td>Test</td><td>10</td></tr><tr><td>Test</td><td>10</td><td>10</td></tr><tr><td></td></tr>';
            
            Test.startTest();
            AddProductOrderCtrl.CheckPastedDateCtrl( anOrder.Id, StringTableData );
            Test.stopTest();
        }
    }
    
    
    @isTest static void UpdateEveryDayPriceTest() {
        
        Account anAccount = [select id from account limit 1][0];
        Product2 Product2Obj = UtilityTest.createGroheProduct();
        Contact con = UtilityTest.CreateContact(anAccount.Id,'Consumer');
        User aUser = UtilityTest.createUser();
        System.runAs(aUser){
            Asset ast = new Asset();
            ast.Name = 'Test Asset';
            ast.Quantity = 1;
            ast.Sub_Channels__c = 'Project';
            ast.AccountId = anAccount.Id;
            ast.Product2Id = Product2Obj.Id;
            ast.PurchaseDate = System.Date.today();
            ast.InstallDate =System.Date.today();
            ast.ContactId = con.Id; 
            insert ast;             
            Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                        Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                        1,
                                                        True)[0];
            aCase.contactId=con.Id;
            aCase.AssetId = ast.Id;
            Update aCase;
            Order anOrder = UtilityTest.CreateOrder(aCase.Id,
                                                    anAccount.Id,
                                                    Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Good_Will_Order').getRecordTypeId(),
                                                    False);
            anOrder.Region__c = 'USA';
            anOrder.Call_Center__c = 'US - Tech';
            anOrder.Order_Type__c = 'Parts in SAP-974440000-ZCRS';
            anOrder.Order_Sub_Type__c = 'ZCRS';
            anOrder.isSent_To_SAP__c=True;
            insert anOrder;
            Test.startTest();
        	Test.setMock(HttpCalloutMock.class, new Informatica_Order_Mock());
            AddProductOrderCtrl.UpdateOrderSimulator( anOrder.Id );
            Test.stopTest();
        }
    }
}