force-app/main/default/objects/Lixil_Config__c/Lixil_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Lixil Config</label>
</CustomObject>

force-app/main/default/objects/Lixil_Config__c/fields/Last_Touch_Days_Limit__c.field-meta.xml
<CustomField>
    <fullName>Last_Touch_Days_Limit__c</fullName>
    <defaultValue>90</defaultValue>
    <label>Last Touch Days Limit</label>
    <precision>16</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lixil_Config__c/fields/Object_for_Last_Touches__c.field-meta.xml
<CustomField>
    <fullName>Object_for_Last_Touches__c</fullName>
    <inlineHelpText>Comma separated list of object that will run to capture last touch dates.</inlineHelpText>
    <label>Object for Last Touches</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/sObjectNoofTouch_BatchSch_Test.cls
@isTest 
public class sObjectNoofTouch_BatchSch_Test {
    static testMethod void testMethod1() 
    {
        List<Account> lstAccount= new List<Account>();
        for(Integer i=0 ;i <6;i++)
        {
            Account acc = new Account();
            acc.Name ='Name'+i;
            acc.Is_Last_Touch_Limit_Hit__c = False;
            lstAccount.add(acc);
        }
        
        insert lstAccount;
        UtilityTest.createAccountTeam(lstAccount[0].Id);
        UtilityTest.createAccountTeam(lstAccount[1].Id);
        insert new Lixil_Config__c(Last_Touch_Days_Limit__c=0,Object_for_Last_Touches__c='Account');
        Test.startTest();
        
        sObjectNoofTouch_BatchSch.scheduleJob();
        
        Test.stopTest();
    }
}