force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SF_Management</label>
</CustomObject>

force-app/main/default/objects/Email__c/fields/Default_Email__c.field-meta.xml
<CustomField>
    <fullName>Default_Email__c</fullName>
    <label>Default Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ODMS_Team_Mapping__c/ODMS_Team_Mapping__c.object-meta.xml
<CustomObject>
    <label>ODMS Team Mapping</label>
    <nameField>
        <displayFormat>OTP{00000}</displayFormat>
        <label>SF ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ODMS Team Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ODMS_Team_Mapping__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>USA/Canada</fullName>
                <isActive>false</isActive>
                <label>USA/Canada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ODMS_Team_Mapping__c/fields/Sub_Team__c.field-meta.xml
<CustomField>
    <fullName>Sub_Team__c</fullName>
    <label>Sub Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bath &amp; Shower - Retail Consumer</fullName>
            </value>
            <value>
                <fullName>Bath &amp; Shower - Trade</fullName>
            </value>
            <value>
                <fullName>BLS - AS/DXV</fullName>
            </value>
            <value>
                <fullName>CA - All Products except Repair Parts</fullName>
            </value>
            <value>
                <fullName>CA - Bath Faucets, Bath Accessories</fullName>
            </value>
            <value>
                <fullName>CA - Customer Master</fullName>
            </value>
            <value>
                <fullName>CA - DC Plant 84</fullName>
            </value>
            <value>
                <fullName>CA - DC - Safety Tubs (167)</fullName>
            </value>
            <value>
                <fullName>CA - Fiat</fullName>
            </value>
            <value>
                <fullName>CA - FIAT, Chinaware, Furniture, commercial chinaware, commercial brass</fullName>
            </value>
            <value>
                <fullName>CA - Order Management - Central</fullName>
            </value>
            <value>
                <fullName>CA - Order Management - East</fullName>
            </value>
            <value>
                <fullName>CA - Order Management - GROHE</fullName>
            </value>
            <value>
                <fullName>CA - Order Management - Retail</fullName>
            </value>
            <value>
                <fullName>CA - Order Management - West</fullName>
            </value>
            <value>
                <fullName>CA - Pricing</fullName>
            </value>
            <value>
                <fullName>CA - Quotes</fullName>
            </value>
            <value>
                <fullName>CA - Repair Parts</fullName>
            </value>
            <value>
                <fullName>CA - Shower Products, Valves, Safety Tub</fullName>
            </value>
            <value>
                <fullName>CA - Shower Walls, Shower Bases, Bathing, Kitchen Faucet, Kitchen Sinks, Kitchen Accessories</fullName>
            </value>
            <value>
                <fullName>CA - Special Select</fullName>
            </value>
            <value>
                <fullName>CA - Warranty</fullName>
            </value>
            <value>
                <fullName>CA - Warranty - American Standard/DXV</fullName>
            </value>
            <value>
                <fullName>CA - Warranty - GROHE</fullName>
            </value>
            <value>
                <fullName>CA - ZClaims / Collections</fullName>
            </value>
            <value>
                <fullName>Chinaware - AS/DXV</fullName>
            </value>
            <value>
                <fullName>Chinaware - Retail Consumer</fullName>
            </value>
            <value>
                <fullName>Chinaware - Toilet Seats</fullName>
            </value>
            <value>
                <fullName>Chinaware - Trade</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Luxury Customer Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ODMS_Team_Mapping__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA - Claims and Collections</fullName>
            </value>
            <value>
                <fullName>CA - Customer Care</fullName>
            </value>
            <value>
                <fullName>CA - Master Data</fullName>
            </value>
            <value>
                <fullName>CA - Pricing</fullName>
            </value>
            <value>
                <fullName>CA - Product Management</fullName>
            </value>
            <value>
                <fullName>CA -Tech Support</fullName>
            </value>
            <value>
                <fullName>Claims and Collections</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Distribution Center</fullName>
            </value>
            <value>
                <fullName>Master Data</fullName>
            </value>
            <value>
                <fullName>Order Entry</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>SOIP</fullName>
            </value>
            <value>
                <fullName>CA - Distribution Center</fullName>
                <isActive>false</isActive>
                <label>CA - Distribution Center</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseExtension_Test.cls
/************************
Author:         Ibad Mohiuddin
Created Date:   08/Aug/2018 
Purpose:        Test Class .

************************MODIFICATION HISTORY**************************************
Added on             Added By               Description
**********************************************************************************
08/Aug/2018          Ibad Mohiuddin   Initial Development /*/

@istest
public class CaseExtension_Test {
    @TestSetup static void createTestSetupData(){
        insert new Email__c(Default_Email__c = 'sf_casemanagement@lixilamericas.com');

        Account anAccount = UtilityTest.createCustomerAccount();
        UtilityTest.createODMSRecord();
        List<sObject> ls = Test.loadData(ODMS_Team_Mapping__c.sObjectType, 'TestData_ODMS');         
        Case aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                                    Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                                    1,
                                                    True)[0];
        aCase.Region__c = 'USA';
        aCase.Team__c = 'Customer Care';
        aCase.Sub_Team__c= 'Luxury Customer Care';
        aCase.Send_ODMS_email__c = True;
        //aCase.Send_email__c=true;
        aCase.Additional_Email_to_be_Included__c='hanif.babar@gettectonic.com;';
        update aCase;
        List<Case> cs = new List<Case>();
        cs.add(aCase);
        CaseExtension.multipleemailstobesend(cs);
        
        aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                               Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Customer_Success').getRecordTypeId(),
                                               1,
                                               True)[0];        
        aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                               Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                               1,
                                               True)[0];
        aCase.Origin = 'Email';
        aCase.Original_Case_Origin__c = 'Email';
        Update aCase;
        aCase = UtilityTest.CreateMultipleCase( anAccount.Id, 
                                               Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Support').getRecordTypeId(),
                                               1,
                                               False)[0];
        aCase.SuppliedName = 'Test';
        aCase.Origin = 'Email';
        aCase.Additional_Email_to_be_Included__c='test@mail.com';
        Insert aCase;
        
    }
    private static testmethod void testMethod1()
    {
        CaseExtension.sendMail(new Map<string,List<String>>{'admin' => new List<String>{'abc@mailinator.com','def@mailinator.com'}});
        CaseExtension.sendEmail(new List<String>{'abc@mailinator.com','def@mailinator.com'},'Test','test');
        //CaseExtension.sendmail();
    }
}