force-app/main/default/objects/SCAR__c/SCAR__c.object-meta.xml
<CustomObject>
    <label>SCAR</label>
    <nameField>
        <displayFormat>SCAR-{0000}</displayFormat>
        <label>SCAR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCAR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCAR__c/fields/Affected_Sites__c.field-meta.xml
<CustomField>
    <fullName>Affected_Sites__c</fullName>
    <inlineHelpText>Identify the potential for shut down, line interruptions, yard recalls, warranty, etc..</inlineHelpText>
    <label>Affected Sites</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCAR__c/fields/Last_Notified_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Last_Notified_Vendor__c</fullName>
    <label>Last Notified Vendor</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SCAR__c/fields/Other_Production_Platform_Risk__c.field-meta.xml
<CustomField>
    <fullName>Other_Production_Platform_Risk__c</fullName>
    <inlineHelpText>Other Product/Platform at Risk ?</inlineHelpText>
    <label>Other Production/Platform Risk</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCAR__c/fields/Problem_Description__c.field-meta.xml
<CustomField>
    <fullName>Problem_Description__c</fullName>
    <inlineHelpText>Describe issue in terms of what, where, when and how many</inlineHelpText>
    <label>Problem Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCAR__c/fields/SCAR_Team_Count__c.field-meta.xml
<CustomField>
    <fullName>SCAR_Team_Count__c</fullName>
    <label>SCAR Team Count</label>
    <summaryFilterItems>
        <field>SCAR_Team__c.Contact_Role__c</field>
        <operation>equals</operation>
        <value>Team Member</value>
    </summaryFilterItems>
    <summaryForeignKey>SCAR_Team__c.SCAR_Form__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SCAR__c/fields/Supplier_Soring_Results__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Soring_Results__c</fullName>
    <inlineHelpText>Sorting Results (Time, Date, Total Number Sorted and Quantity Rejected)</inlineHelpText>
    <label>Supplier Sorting Results</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCAR__c/fields/What_actions_were_taken_to_Immediately__c.field-meta.xml
<CustomField>
    <fullName>What_actions_were_taken_to_Immediately__c</fullName>
    <inlineHelpText>What actions were taken to immediately protect the customer and contain any suspect inventory?</inlineHelpText>
    <label>What actions were taken to Immediately</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCAR_Team__c/SCAR_Team__c.object-meta.xml
<CustomObject>
    <label>SCAR Team</label>
    <nameField>
        <label>SCAR Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCAR Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SCAR_Vendor_Form_Email__c/SCAR_Vendor_Form_Email__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SCAR Vendor Form Email</label>
</CustomObject>

force-app/main/default/objects/SCAR_Vendor_Form_Email__c/fields/First_Notification_Days__c.field-meta.xml
<CustomField>
    <fullName>First_Notification_Days__c</fullName>
    <label>First Notification Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCAR_Vendor_Form_Email__c/fields/Second_Notification_Days__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification_Days__c</fullName>
    <label>Second Notification Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScarVendorFormControllerTest.cls
/* Author		: Abid Raza
   Date			: 13th-Oct-2018
   Description	: Test class to cover coverage of ScarVenforFormController class, Scar Trigger, ScarVendorFormEmailBatch and ScarVendorFormEmailBatch Schecular.
*/

@isTest
public class ScarVendorFormControllerTest 
{
	//Create Sample Data 
	@TestSetup static void createTestSetupData()
    {
        Account DealerAccount = UtilityTest.createDealerAccount();
        Contact WholesalerContact = UtilityTest.CreateContact(DealerAccount.Id,'Wholesaler');
        SCAR__c Scar1 =  UtilityTest.createScar(true,DealerAccount.Id,WholesalerContact.Id);
        SCAR_Team__c st1 = UtilityTest.CreateScarTeam(Scar1.Id);
        SCAR_Team__c st2 = UtilityTest.CreateScarTeam(Scar1.Id);
        SCAR__c Scar2 =  UtilityTest.createScar(true,DealerAccount.Id,WholesalerContact.Id);
    }
    
    @isTest static void TestScarVendorFormController()
    { 
        List<Scar__c> scar = [Select Id,Name,SCAR_Team_Count__c,Last_Notified_Vendor__c,Affected_Sites__c,Problem_Description__c,What_actions_were_taken_to_Immediately__c,Other_Production_Platform_Risk__c,Supplier_Soring_Results__c from Scar__c limit 2];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(scar[0]);
        ApexPages.currentPage().getParameters().put('id',scar[0].id);
        ScarVendorFormController Svfc = new ScarVendorFormController();
        
        Svfc.addRows();
        Svfc.method1();
        Svfc.method1();
        Svfc.method1();
        Svfc.method1();
        Svfc.method1();
        Svfc.method1();
        Svfc.method1();
        Svfc.method1();
        Svfc.Save();
        
        for(Scar__c scr: scar)
        {
            if(scr.SCAR_Team_Count__c > 0)
            {
                scr.Affected_Sites__c = 'abc';
        		scr.Problem_Description__c = 'abc';
        		scr.What_actions_were_taken_to_Immediately__c = 'abc';
        		scr.Other_Production_Platform_Risk__c = 'abc';
        		scr.Supplier_Soring_Results__c = 'abc';
                scr.Last_Notified_Vendor__c = Date.today().addDays(-10);
            }
            else
            {
                scr.Last_Notified_Vendor__c = Date.today().addDays(-2);
            }
            
        }
        Update scar;
        
        SCAR_Vendor_Form_Email__c svfe = new SCAR_Vendor_Form_Email__c();
        svfe.First_Notification_Days__c = 2;
        svfe.Second_Notification_Days__c = 10;
        insert svfe;
        Database.executeBatch(new SendSCARFormToVendorEmailBatch());
        
        String CRON_EXP = '0 0 0 1 1 ? 2025';  
        String jobId = System.schedule('testScheduledApex', CRON_EXP, new SendSCARFormToVendorEmailBatchSchedular());
        
    }
}