force-app/main/default/objects/Industry_Region_Wise_Rep__c/Industry_Region_Wise_Rep__c.object-meta.xml
<CustomObject>
    <label>Industry/Region Wise Rep</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Industry/Region Wise Rep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry/Region Wise Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Northwest</fullName>
            </value>
            <value>
                <fullName>Southcentral</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
            <value>
                <fullName>MRO</fullName>
            </value>
            <value>
                <fullName>Transfer DC Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Industry_Region_Wise_Rep__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Industry_Region_Wise_Reps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTrgTest.cls
@IsTest
public class LeadTrgTest 
{
	@TestSetup static void createTestSetupData()
    {
        Account Customeracct = UtilityTest.createDealerAccount();
        Lead lea = UtilityTest.createLead();
        UtilityTest.CreateAgencyZipCodeAssignment();
    }
    
    // Test Method to convert lead to account.
    @isTest static void testCheckAccountRecordTypeForLead()
    {
        Test.startTest();
        	Account acc = [select Id, Name from Account limit 1];
            Lead lea = [Select Id,Name,LeadSource,status,Region__c,PostalCode from Lead limit 1];
        	Industry_Region_Wise_Rep__c ind = new Industry_Region_Wise_Rep__c();
        	ind.Region__c = 'Midwest';
        	ind.User__c = Userinfo.getUserId();
        	insert ind;
        	lea.PostalCode = '220067';
        	Update lea;
        	
        	lea.LeadSource = 'Pardot';
        	lea.status = 'Qualified';
        	Update lea;
            
        	Database.LeadConvert lc = new database.LeadConvert();
            LeadStatus status = [SELECT Id,MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];
            lc.setLeadId(lea.Id);
            lc.setDoNotCreateOpportunity(true);
            lc.setAccountId(acc.id);
            lc.setOverwriteLeadSource(true);
        	lc.setConvertedStatus(status.MasterLabel);
        	
        	Database.LeadConvertResult lcr = Database.convertLead(lc);
        	System.assertEquals(true, lcr.isSuccess());

        Test.stopTest();
    }
}