force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Account</label>
</CustomObject>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rep Agencies</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Agency_Account__c.field-meta.xml
<CustomField>
    <fullName>Agency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agencies (Agency Account)</relationshipLabel>
    <relationshipName>Agencies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>DXV</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Grohe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/Agency_Zip_Code_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a setup object which will be used to assign the agencies contact based on the zip codes</description>
    <label>Agency Zip Code Assignment</label>
    <nameField>
        <label>Agency Zip Code Assignment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies Zip Code Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/ASRep__c.field-meta.xml
<CustomField>
    <fullName>ASRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the ASRep for the current zip code and region</description>
    <inlineHelpText>ASRep Account</inlineHelpText>
    <label>ASRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ASRep_Account</relationshipLabel>
    <relationshipName>ASRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/DXVRep__c.field-meta.xml
<CustomField>
    <fullName>DXVRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the DXVRep for the current zip code and region</description>
    <inlineHelpText>DXVRep Account</inlineHelpText>
    <label>DXVRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DXVRep_Account</relationshipLabel>
    <relationshipName>DXVRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/FiatRep__c.field-meta.xml
<CustomField>
    <fullName>FiatRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the FiatRep for the current zip code and region</description>
    <inlineHelpText>FiatRep Account</inlineHelpText>
    <label>FiatRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FiatRep_Account</relationshipLabel>
    <relationshipName>FiatRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/GroheRep__c.field-meta.xml
<CustomField>
    <fullName>GroheRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the GroheRep for the current zip code and region</description>
    <inlineHelpText>GroheRep Account</inlineHelpText>
    <label>GroheRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GroheRe_Account</relationshipLabel>
    <relationshipName>GroheRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Recalculate_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Assignment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be used to recalculate the agencies, and will update the record under the account.</description>
    <inlineHelpText>Check this box if recalculation required. 
NOTE: recalculation may take time to be completely processed due to volume of data.</inlineHelpText>
    <label>Recalculate Assignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This picklist will be used to show the Type of the zip code</description>
    <inlineHelpText>Type of ZipCode</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PO BOX</fullName>
            </value>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>UNIQUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Influencers__c/Influencers__c.object-meta.xml
<CustomObject>
    <label>Influencers</label>
    <nameField>
        <displayFormat>INF-{0000000}</displayFormat>
        <label>Influencer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Influencers__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Influencers</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture project opportunities.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Agency_Zip_Code_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Agency_Zip_Code_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Zip Code Assignment</label>
    <referenceTo>Agency_Zip_Code_Assignment__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Project address&#39; zip/postal code</description>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Agency__c/Project_Agency__c.object-meta.xml
<CustomObject>
    <label>Project Agency</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Project Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Agency__c/fields/Agency_Zip_Code_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Agency_Zip_Code_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Zip Code Assignment</label>
    <referenceTo>Agency_Zip_Code_Assignment__c</referenceTo>
    <relationshipLabel>Project Agencies</relationshipLabel>
    <relationshipName>Project_Agencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Agency__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Agencies</relationshipLabel>
    <relationshipName>Project_Agencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Agency__c/fields/Project_Agency__c.field-meta.xml
<CustomField>
    <fullName>Project_Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Agencies</relationshipLabel>
    <relationshipName>Project_Agencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Agency__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>DXV</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Grohe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgencyZipCodeAssignmentTrgHelper.cls
/************************
Author:         Azfer Pervaiz
Created Date:   1/June/2018  
Purpose:        This class is the Helper class for the AgencyZipCodeAssignmentTrg Trigger.

************************MODIFICATION HISTORY**************************************
Added on             Added By               Description
**********************************************************************************
1/June/2018          Azfer Pervaiz          Initial Development 
***********************************************************************************/
public class AgencyZipCodeAssignmentTrgHelper {

  public static Set<String> SetZipCode = new Set<String>();
  public static Map<String, Agency_Zip_Code_Assignment__c> MapZipToAZCA = new Map<String, Agency_Zip_Code_Assignment__c>();
  
  //AZCA = Agency Zip Code Assignment
  public void UpdateRecalculationCheckbox(List<Agency_Zip_Code_Assignment__c> paramListAZCA){
    for( Agency_Zip_Code_Assignment__c AZCAObj : paramListAZCA )
    {
      AZCAObj.Recalculate_Assignment__c = false;  
    }
  }

    public void RecalculateAgencyAssignments( Map<String, Agency_Zip_Code_Assignment__c> paramMapZipToAZCA , set<string> paramSetZipCode ){
        
        List<Agency__c> ListAgencyToUpdate = new List<Agency__c>();
        Agency_Zip_Code_Assignment__c AZCAObj;
        
        system.debug(json.serialize([SELECT Id, Account__c,  Account__r.ShippingPostalCode, Agency_Account__c, Type__c 
                                    FROM Agency__c ]));
         system.debug(paramSetZipCode);
        for( Agency__c AgencyObj : [SELECT Id, Account__c,  Account__r.ShippingPostalCode, Agency_Account__c, Type__c 
                                    FROM Agency__c 
                                    WHERE Account__r.ShippingPostalCode IN : paramSetZipCode ])
        {
            AZCAObj = paramMapZipToAZCA.get( AgencyObj.Account__r.ShippingPostalCode );
            
            if( AgencyObj.Type__c == 'AS' ){
                AgencyObj.Agency_Account__c = AZCAObj.ASRep__c;
            }else if( AgencyObj.Type__c == 'DXV' ){
                AgencyObj.Agency_Account__c = AZCAObj.DXVRep__c;
            }else if( AgencyObj.Type__c == 'Fiat' ){
                AgencyObj.Agency_Account__c = AZCAObj.FiatRep__c;
            }else if( AgencyObj.Type__c == 'Grohe' ){
                AgencyObj.Agency_Account__c = AZCAObj.GroheRep__c;
            }
            
            ListAgencyToUpdate.add( AgencyObj );
            
        }
        if( ListAgencyToUpdate.size() > 0 ){
            try{
                update ListAgencyToUpdate;
            }catch(Exception Ex){
                system.debug('Exception :: '+Ex.getMessage());
            }
        }
    }  
    public void RecalculateAgencyAssignmentsforProjects( Map<String, Agency_Zip_Code_Assignment__c> paramMapZipToAZCA , set<string> paramSetZipCode ){
    
    List<Project_Agency__c> ListAgencyToUpdate = new List<Project_Agency__c>();
    Agency_Zip_Code_Assignment__c AZCAObj;
	
    for( Project_Agency__c AgencyObj : [SELECT Id, Project__c ,Project__r.Postal_Code__c,  Project_Agency__c, Type__c 
		FROM Project_Agency__c WHERE Project__r.Postal_Code__c IN:paramSetZipCode ])
    {
      AZCAObj = paramMapZipToAZCA.get( AgencyObj.Project__r.Postal_Code__c );
      
      if( AgencyObj.Type__c == 'AS' ){
        AgencyObj.Project_Agency__c = AZCAObj.ASRep__c;
      }else if( AgencyObj.Type__c == 'DXV' ){
        AgencyObj.Project_Agency__c = AZCAObj.DXVRep__c;
      }else if( AgencyObj.Type__c == 'Fiat' ){
        AgencyObj.Project_Agency__c = AZCAObj.FiatRep__c;
      }else if( AgencyObj.Type__c == 'Grohe' ){
        AgencyObj.Project_Agency__c = AZCAObj.GroheRep__c;
      }

      ListAgencyToUpdate.add( AgencyObj );
    }
    
    if( ListAgencyToUpdate.size() > 0 ){
      try{
        update ListAgencyToUpdate;
      }catch(Exception Ex){
        system.debug('Exception :: '+Ex.getMessage());
      }
    }
  }  
    
}