force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Account</label>
</CustomObject>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rep Agencies</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Agency_Account__c.field-meta.xml
<CustomField>
    <fullName>Agency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agencies (Agency Account)</relationshipLabel>
    <relationshipName>Agencies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/onAgencySave_Test.cls
@isTest
public class onAgencySave_Test {
    @isTest static void CreateAgency()
    {
        Account acc1 = UtilityTest.createCustomerAccount();
        Account acc2 = UtilityTest.createAgencyAccount();
        Agency__c a = new Agency__c();
        a.Account__c = acc1.id;
        a.Agency_Account__c= acc2.id;
        insert a;
        
        Account acc3 = UtilityTest.createAgencyAccount();
        Agency__c a1 = new Agency__c();
        a1.Account__c = acc1.id;
        a1.Agency_Account__c= acc2.id;
        insert a1;
        
    }
}