force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Account</label>
</CustomObject>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rep Agencies</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Agency_Account__c.field-meta.xml
<CustomField>
    <fullName>Agency_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agencies (Agency Account)</relationshipLabel>
    <relationshipName>Agencies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>DXV</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Grohe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/Agency_Zip_Code_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a setup object which will be used to assign the agencies contact based on the zip codes</description>
    <label>Agency Zip Code Assignment</label>
    <nameField>
        <label>Agency Zip Code Assignment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies Zip Code Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/ASRep__c.field-meta.xml
<CustomField>
    <fullName>ASRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the ASRep for the current zip code and region</description>
    <inlineHelpText>ASRep Account</inlineHelpText>
    <label>ASRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ASRep_Account</relationshipLabel>
    <relationshipName>ASRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/DXVRep__c.field-meta.xml
<CustomField>
    <fullName>DXVRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the DXVRep for the current zip code and region</description>
    <inlineHelpText>DXVRep Account</inlineHelpText>
    <label>DXVRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DXVRep_Account</relationshipLabel>
    <relationshipName>DXVRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/FiatRep__c.field-meta.xml
<CustomField>
    <fullName>FiatRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the FiatRep for the current zip code and region</description>
    <inlineHelpText>FiatRep Account</inlineHelpText>
    <label>FiatRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FiatRep_Account</relationshipLabel>
    <relationshipName>FiatRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/GroheRep__c.field-meta.xml
<CustomField>
    <fullName>GroheRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to show which Account is the GroheRep for the current zip code and region</description>
    <inlineHelpText>GroheRep Account</inlineHelpText>
    <label>GroheRep</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GroheRe_Account</relationshipLabel>
    <relationshipName>GroheRep_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This picklist will show the region values</description>
    <inlineHelpText>Regions</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This picklist will be used to show the Type of the zip code</description>
    <inlineHelpText>Type of ZipCode</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PO BOX</fullName>
            </value>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>UNIQUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <description>This field will be used to store the zip code for the agency assginment</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Zip Codes</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/Team_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Team Assignment Rule</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Team Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Team Assignment Rules</relationshipLabel>
    <relationshipName>Team_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/Assignment_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Type__c</fullName>
    <label>Assignment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Account Team</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Initiative</fullName>
            </value>
            <value>
                <fullName>Showroom/Display</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/RecordTypeDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeDeveloperName__c</fullName>
    <description>Field which will be used for automation in developer name</description>
    <formula>RecordType.DeveloperName</formula>
    <label>Record Type Developer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This picklist will be used for team assignment based on the region</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Chief Sales Officer</fullName>
            </value>
            <value>
                <fullName>Director National Accounts MRO</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director Projects</fullName>
            </value>
            <value>
                <fullName>MRO National Account Manage</fullName>
            </value>
            <value>
                <fullName>National Account Manager</fullName>
            </value>
            <value>
                <fullName>National Showroom Manager</fullName>
            </value>
            <value>
                <fullName>Regional Project Manager</fullName>
            </value>
            <value>
                <fullName>Regional Showroom Manager</fullName>
            </value>
            <value>
                <fullName>Sales Support Manager</fullName>
            </value>
            <value>
                <fullName>Sales Support Specialist</fullName>
            </value>
            <value>
                <fullName>Showroom Manager</fullName>
            </value>
            <value>
                <fullName>VP Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/SubChannel__c.field-meta.xml
<CustomField>
    <fullName>SubChannel__c</fullName>
    <description>This field will be used for the assignment of the account team</description>
    <inlineHelpText>values should be comma separated.
E.g. A,B,C,D</inlineHelpText>
    <label>Sub Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Assignment_Rules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Assignment_Rule__c/recordTypes/Account_Team.recordType-meta.xml
<RecordType>
    <fullName>Account_Team</fullName>
    <active>true</active>
    <description>This record type will be used for creating the assignment rules for the Account Team</description>
    <label>Account Team</label>
</RecordType>

force-app/main/default/objects/Team_Assignment_Rule__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <description>This record type will be used for creating the assignment rules for the Opportunity Team</description>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/classes/AccountTrgHelper.cls
/************************
Author:         Azfer Pervaiz
Created Date:   30/May/2018 
Purpose:        This class is the Helper class for the Account Trigger.

************************MODIFICATION HISTORY**************************************
Added on             Added By               Description
**********************************************************************************
30/May/2018          Azfer Pervaiz          Initial Development 
***********************************************************************************/
public class AccountTrgHelper{

    static Set<String> SetAccountRecordTypeToAssignAgencies = new Set<String>();
    static Set<String> SetAccountRecordTypeToAssignTeam = new Set<String>();
    static Set<String> SetAccountRecordTypeToNotAssignRegion = new Set<String>();
    
    static Set<Account> SetAccountToAssignRegion = new Set<Account>();
    static Set<Account> SetAccountToAssignAgencies = new Set<Account>();
    static Set<Account> SetAccountToAssignTeam = new Set<Account>();

    static Set<String> SetAccountPostalCode = new Set<String>();
    
    static Set<String> SetAccountRegion = new Set<String>();
    static Set<String> SetAccountRecordType = new Set<String>();

    static Set<Id> SetAccountToRemoveAgencies = new Set<Id>();
    static Set<Id> SetAccountToRemoveTeam = new Set<Id>();
    
    static Map<String,Agency_Zip_Code_Assignment__c> MapZipToRegion = new Map<String,Agency_Zip_Code_Assignment__c>();
    static Map<String,List<Team_Assignment_Rule__c>> MapAccountTeam = new Map<String,List<Team_Assignment_Rule__c>>();

    //Constructor
    public AccountTrgHelper(){
        populateRecordTypeSet();        
    }

    //Method To Populate Set collection
    private void populateRecordTypeSet(){

        SetAccountRecordTypeToAssignAgencies.add( 'dealer' );
        SetAccountRecordTypeToAssignAgencies.add( 'influencer' );
        
        SetAccountRecordTypeToAssignTeam.add( 'agency' );
        SetAccountRecordTypeToAssignTeam.add( 'customer' );
        SetAccountRecordTypeToAssignTeam.add( 'dealer' );
        SetAccountRecordTypeToAssignTeam.add( 'influencer' );

        SetAccountRecordTypeToNotAssignRegion.add( 'buying_group' );
        SetAccountRecordTypeToNotAssignRegion.add( 'customer' );

    }

    public void onBeforeInsert(List<Account> newObjects, Map<Id, Account> newMap){
        for( Account AccountObj : newObjects ){
            
            if( !SetAccountRecordTypeToNotAssignRegion.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) &&
                AccountObj.ShippingPostalCode != null ){

                SetAccountToAssignRegion.add( AccountObj );
            }else{
                AccountObj.ShippingPostalCode = null; 
                if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                    SetAccountToRemoveAgencies.add( AccountObj.Id );               
                }
                SetAccountToRemoveTeam.add( AccountObj.Id );
            }

            if( AccountObj.ShippingPostalCode != null ){
                SetAccountPostalCode.add( AccountObj.ShippingPostalCode );
            }else{
                AccountObj.ShippingPostalCode = null;     
                if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                    SetAccountToRemoveAgencies.add( AccountObj.Id );               
                }
                SetAccountToRemoveTeam.add( AccountObj.Id );                        
            }

            if( AccountObj.RecalculateTeamAssignment__c ){
            
                AccountObj.RecalculateTeamAssignment__c = false;
                
                SetAccountToAssignAgencies.add( AccountObj );
                SetAccountToAssignTeam.add( AccountObj );
                if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                    SetAccountToRemoveAgencies.add( AccountObj.Id );               
                }
                SetAccountToRemoveTeam.add( AccountObj.Id );

            }
            SetAccountRegion.add( AccountObj.Sales_Region__c );
            SetAccountRecordType.add( AccountObj.RecordTypeDeveloperName__c );

        }
        if( SetAccountPostalCode.size() > 0 ){
            PopulatePostalCodeMap( SetAccountPostalCode );
        }

        if( SetAccountToAssignRegion.size() > 0 ){
            AssignRegionToAccount( SetAccountToAssignRegion );
        }

        if( SetAccountRegion.size() > 0 ){
            PopulateTeamMap( SetAccountRegion, SetAccountRecordType );
        }

        if( SetAccountRegion.size() > 0 ){
            AssignRegionalShowroomManager( SetAccountToAssignRegion );
        }        
    } 

    public void OnAfterInsert(List<Account> newObjects, Map<Id, Account> newMap){
        Set<Id> setAcctIDs = new Set<Id>();

        for( Account AccountObj : newObjects )
        {
            
            if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) &&
                AccountObj.ShippingPostalCode != null ){

                SetAccountToAssignAgencies.add( AccountObj );

            }

            if( AccountObj.Sales_Region__c != null && SetAccountRecordTypeToAssignTeam.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                SetAccountToAssignTeam.add( AccountObj );
            }
            
            setAcctIDs.add(AccountObj.Id);
        }
        if (setAcctIDs != null && setAcctIDs.size() > 0)
        {
            BoxIntegrationUtil.createFolderinBox (setAcctIDs, 'Account');
        }

        if( SetAccountToRemoveAgencies.size() > 0 ){
            RemoveAgencies( SetAccountToRemoveAgencies );
        }

        if( SetAccountToAssignAgencies.size() > 0 ){
            AssignAgencies( SetAccountToAssignAgencies );
        }

        if( SetAccountToAssignTeam.size() > 0 ){
            AssignAccountTeam( SetAccountToAssignTeam );
        }
    }

    public void onBeforeUpdate(List<Account> oldObjects, List<Account> newObjects, Map<Id, Account> oldMap, Map<Id, Account> newMap){
        Account OldAccount;
        for( Account AccountObj : newObjects ){
            
            OldAccount = oldMap.get( AccountObj.Id );

            if( !SetAccountRecordTypeToNotAssignRegion.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) &&
                AccountObj.ShippingPostalCode != null && OldAccount.ShippingPostalCode != AccountObj.ShippingPostalCode ){

                SetAccountToAssignRegion.add( AccountObj );    
                if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                    SetAccountToRemoveAgencies.add( AccountObj.Id );               
                }
                SetAccountToRemoveTeam.add( AccountObj.Id );

            }else  if( AccountObj.ShippingPostalCode == null ){
            
                AccountObj.ShippingPostalCode = null;     
                if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                    SetAccountToRemoveAgencies.add( AccountObj.Id );               
                }
                SetAccountToRemoveTeam.add( AccountObj.Id );                          
            
            }

            if( AccountObj.ShippingPostalCode != null ){

                SetAccountPostalCode.add( AccountObj.ShippingPostalCode );
            
            }else  if( AccountObj.ShippingPostalCode == null ){
            
                AccountObj.ShippingPostalCode = null;                
                if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                    SetAccountToRemoveAgencies.add( AccountObj.Id );               
                }
                SetAccountToRemoveTeam.add( AccountObj.Id );               
            
            }

            if( AccountObj.RecalculateTeamAssignment__c ){
                
                AccountObj.RecalculateTeamAssignment__c = false;

                SetAccountToAssignAgencies.add( AccountObj );
                SetAccountToAssignTeam.add( AccountObj );
                if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){
                    SetAccountToRemoveAgencies.add( AccountObj.Id );               
                }
                SetAccountToRemoveTeam.add( AccountObj.Id );

            }

            SetAccountRegion.add( AccountObj.Sales_Region__c );
            SetAccountRecordType.add( AccountObj.RecordTypeDeveloperName__c );

        }

        if( SetAccountPostalCode.size() > 0 ){
            PopulatePostalCodeMap( SetAccountPostalCode );
        }

        if( SetAccountToAssignRegion.size() > 0 ){
            AssignRegionToAccount( SetAccountToAssignRegion );
        }

        if( SetAccountRegion.size() > 0 ){
            PopulateTeamMap( SetAccountRegion, SetAccountRecordType );
        }

        if( SetAccountRegion.size() > 0 ){
            AssignRegionalShowroomManager( SetAccountToAssignRegion );
        }
		
        // Added by Hanif to call Account Sub Type update for Integration
        setAccountSubType(newMap);
    }   

    public void onAfterUpdate(List<Account> oldObjects, List<Account> newObjects, Map<Id, Account> oldMap, Map<Id, Account> newMap){
        Account OldAccount;
        Set<Id> SetAccountId = new Set<Id>();
        for( Account AccountObj : newObjects ){
            
            OldAccount = oldMap.get( AccountObj.Id );
            
            if( SetAccountRecordTypeToAssignAgencies.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) &&
                AccountObj.ShippingPostalCode != null && OldAccount.ShippingPostalCode != AccountObj.ShippingPostalCode ){
                SetAccountToAssignAgencies.add( AccountObj );
                SetAccountId.add( AccountObj.Id );
            
            }
            if( AccountObj.Sales_Region__c != null && AccountObj.RecordTypeId != null && 
                ( AccountObj.Sales_Region__c != OldAccount.Sales_Region__c || AccountObj.RecordTypeId != OldAccount.RecordTypeId ) &&  
                SetAccountRecordTypeToAssignTeam.contains( AccountObj.RecordTypeDeveloperName__c.toLowerCase() ) ){

                SetAccountToRemoveTeam.add( AccountObj.Id );
                SetAccountToAssignTeam.add( AccountObj );
            }
        }
        if( SetAccountToRemoveAgencies.size() > 0 ){
            RemoveAgencies( SetAccountToRemoveAgencies );
        }               
        
        if( SetAccountToAssignAgencies.size() > 0 ){
            AssignAgencies( SetAccountToAssignAgencies );
            UpdateChildOpportunity( SetAccountId );
        }

        if( SetAccountToRemoveTeam.size() > 0 ){
            RemoveAccountTeam( SetAccountToRemoveTeam );
        }

        if( SetAccountToAssignTeam.size() > 0 ){
            AssignAccountTeam( SetAccountToAssignTeam );
        }
    }


    //This method will be used to populate the regions map for the account
    private void PopulatePostalCodeMap( Set<String> paramSetAccountPostalCode ){
        MapZipToRegion = new Map<String,Agency_Zip_Code_Assignment__c>();

        for( Agency_Zip_Code_Assignment__c AZCAObj : [SELECT ASRep__c, DXVRep__c, FiatRep__c, GroheRep__c, Region__c, ZipCode__c 
                                                        FROM Agency_Zip_Code_Assignment__c 
                                                        WHERE ZipCode__c IN : paramSetAccountPostalCode ])
        {
            MapZipToRegion.put( AZCAObj.ZipCode__c, AZCAObj );
        }

    }

    //This method will be used to populate map for the account team
    private void PopulateTeamMap( Set<String> paramSetRegions, Set<String> paramSetAccountRecordType ){
        MapAccountTeam = new Map<String,List<Team_Assignment_Rule__c>>();
    
        for(Team_Assignment_Rule__c TARObj :[SELECT Id, Account__c, Assignment_Type__c, Role__c, 
                                                SubChannel__c, Region__c, Team_Member__c, User__c
                                            FROM Team_Assignment_Rule__c
                                            WHERE RecordType.DeveloperName = 'Account_Team'
                                            AND Assignment_Type__c IN : paramSetAccountRecordType
                                            AND Region__c IN : paramSetRegions])
        {
            if( MapAccountTeam.get( TARObj.Assignment_Type__c+'-'+TARObj.Region__c ) == null ){
                MapAccountTeam.put( TARObj.Assignment_Type__c+'-'+TARObj.Region__c, new List<Team_Assignment_Rule__c>{ TARObj } );
            }else{
                List<Team_Assignment_Rule__c> TSRTempObj = MapAccountTeam.get( TARObj.Assignment_Type__c+'-'+TARObj.Region__c );
                TSRTempObj.add( TARObj );
            }
        
        }
    
    }

    //This method will be used to assign the Region to Account
    private void AssignRegionToAccount( Set<Account> paramSetAccountToAssignRegion ){
        for(Account AccountObj : paramSetAccountToAssignRegion )
        {
            if( MapZipToRegion.get( AccountObj.ShippingPostalCode ) != null ){
                AccountObj.Sales_Region__c = MapZipToRegion.get( AccountObj.ShippingPostalCode ).Region__c;
                SetAccountRegion.add( AccountObj.Sales_Region__c );
            }else{
                AccountObj.Sales_Region__c = null;
            }
        }
    }

    //This method will assigne the Regional ShowRoom manager to account
    //RSM = Regional ShowRoom manager
    private void AssignRegionalShowroomManager( Set<Account> paramSetAccountToAssignRSM ){
        for( Account AccountObj : paramSetAccountToAssignRSM )
        {
            String Key = AccountObj.RecordTypeDeveloperName__c+'-'+AccountObj.Sales_Region__c;
            if( MapAccountTeam.get( Key ) != null ){
                for( Team_Assignment_Rule__c TARObj : MapAccountTeam.get( Key ) )
                {
                    if( TARObj.Role__c == 'Regional Showroom Manager' ){
                        if( TARObj.Account__c == AccountObj.ParentId ){
                            AccountObj.Regional_Showroom_Manager2__c = TARObj.Team_Member__c;
                        }else if( TARObj.Account__c == null ) {
                            AccountObj.Regional_Showroom_Manager2__c = TARObj.Team_Member__c;
                        }
                    }
                }
            }
        }
    }

    //This method will be used to remove the agencyies
    private void RemoveAgencies( Set<Id> paramSetAccountId ){

        try{
           delete [SELECT Id FROM Agency__c WHERE Account__c IN : paramSetAccountId ];
        }catch(Exception Ex){
            system.debug('Exception :: '+Ex.getMessage());
        }
    }

    //This method will be used to assign the Agencies to Account
    private void AssignAgencies( Set<Account> paramSetAccountToAssignAgencies ){
        List<Agency__c> ListOfAgencyToCreate = new List<Agency__c>();
        
        for(Account AccountObj : paramSetAccountToAssignAgencies )
        {
            if( MapZipToRegion.get( AccountObj.ShippingPostalCode ) != null ){

                ListOfAgencyToCreate.addAll( GenerateAgencies( AccountObj , MapZipToRegion.get( AccountObj.ShippingPostalCode ) ) );
            }
        }
    
        if( ListOfAgencyToCreate.size() > 0 ){
            try{
               insert ListOfAgencyToCreate;
            }catch(Exception Ex){
                system.debug('Exception :: '+Ex.getMessage());
            }
        }
    }

    //This method will be used to generate agency records
    private List<Agency__c> GenerateAgencies(Account paramAccount, Agency_Zip_Code_Assignment__c paramAZCA ){

        List<Agency__c> ListToReturn = new List<Agency__c>();

        if( paramAZCA.ASRep__c != null ){
            ListToReturn.add ( new Agency__c( Account__c = paramAccount.Id, Agency_Account__c = paramAZCA.ASRep__c, Type__c = 'AS' ) ); 
        }

        if( paramAZCA.DXVRep__c != null ){
            ListToReturn.add ( new Agency__c( Account__c = paramAccount.Id, Agency_Account__c = paramAZCA.DXVRep__c, Type__c = 'DXV' ) ); 
        }

        if( paramAZCA.FiatRep__c != null ){
            ListToReturn.add ( new Agency__c( Account__c = paramAccount.Id, Agency_Account__c = paramAZCA.FiatRep__c, Type__c = 'Fiat' ) ); 
        }

        if( paramAZCA.GroheRep__c != null ){
            ListToReturn.add ( new Agency__c( Account__c = paramAccount.Id, Agency_Account__c = paramAZCA.GroheRep__c, Type__c = 'Grohe' ) ); 
        }

        return ListToReturn;

    }

    //This method will be used to delete account team
    private void RemoveAccountTeam( Set<Id> paramSetAccountId ){

        try{
           delete [SELECT Id FROM AccountTeamMember WHERE AccountId IN : paramSetAccountId ];
        }catch(Exception Ex){
            system.debug('Exception :: '+Ex.getMessage());
        }
    }

    //This method will used to assign account team
    private void AssignAccountTeam( Set<Account> paramSetAccount){
        
        List<AccountTeamMember> ListATMtoCreate = new List<AccountTeamMember>();
        for( Account AccountObj : paramSetAccount )
        {
            String Key = AccountObj.RecordTypeDeveloperName__c+'-'+AccountObj.Sales_Region__c;

            if( MapAccountTeam.get( Key ) != null ){
                for( Team_Assignment_Rule__c TARObj : MapAccountTeam.get( Key ) )
                {
                    if( TARObj.Account__c == AccountObj.ParentId && AccountObj.ParentId != null && 
                        AccountObj.Sub_Channel__c != null && TARObj.SubChannel__c != null && AccountObj.Sub_Channel__c.contains( TARObj.SubChannel__c ) ){

                        ListATMtoCreate.add( GenerateMember( AccountObj.Id, TARObj) );

                    }else if( TARObj.Account__c == AccountObj.ParentId && AccountObj.ParentId != null && 
                        TARObj.SubChannel__c == null && AccountObj.Sub_Channel__c == null ){

                        ListATMtoCreate.add( GenerateMember( AccountObj.Id, TARObj) );

                    }else if ( TARObj.Account__c == null ){

                        ListATMtoCreate.add( GenerateMember( AccountObj.Id, TARObj) );

                    }
                }
            }
        }
        if( ListATMtoCreate.size() > 0 ){
            try{
               insert ListATMtoCreate;
            }catch(Exception Ex){
                system.debug('Exception :: '+Ex.getMessage());
            } 
        }
    }

    //This method will return a Account Team Member reocrd
    private AccountTeamMember GenerateMember(Id paramAccountId, Team_Assignment_Rule__c paramTARObj ){
        return ( new AccountTeamMember ( AccountAccessLevel = 'Edit', AccountId = paramAccountId, CaseAccessLevel = 'Edit', 
                                            ContactAccessLevel = 'Edit', OpportunityAccessLevel = 'Edit', TeamMemberRole = paramTARObj.Role__c, 
                                            UserId = paramTARObj.Team_Member__c ) );       
    }

    //This methos will update the child opporutnity when region is chagnes
    private void UpdateChildOpportunity( Set<Id> paramSetAccountId ){
        List<opportunity> ListOpportunityToUpdate = new List<opportunity>();

        for( Opportunity OpportunityObj :[SELECT 
                                                Id, AccountSalesRegionUpdated__c 
                                        FROM Opportunity
                                        WHERE AccountId IN : paramSetAccountId] )
        {
            OpportunityObj.AccountSalesRegionUpdated__c = true;
            ListOpportunityToUpdate.add( OpportunityObj );
        }

        if( ListOpportunityToUpdate.size() > 0 ){
            try{
                update ListOpportunityToUpdate;
            }catch(Exception Ex){
                system.debug('Exception :: '+Ex.getMessage());
            }
        }
    }
    // Add by Hanif to set Account subtype recieved from partnerfunction
    private void setAccountSubType(Map<Id, Account> newMap){
        // Get last account subt type value
        List<Account> lstAccount = [Select Account_Subtype__c From Account Where id = :newMap.keySet()];
        
        for(Account anAccount:lstAccount){
            // Account sub type from old, new and Integration Partnerfunction field
            Account trgAccount  = newMap.get(anAccount.Id);
            String newAST = trgAccount.Account_Subtype__c;  
            //String existingAST = anAccount.Account_Subtype__c;
            String partnerFunction = trgAccount.Partner_Function__c;
            String strAccountSubType = newAST+';'/*+existingAST+';'*/+partnerFunction;
            strAccountSubType.removeEnd(';');
            strAccountSubType.removeStart(';');
            // Make AST unique
            List<String> lstAST = strAccountSubType.split(';');
            Set<String> setAST = new Set<String>();
            for (string AST:lstAST){
                system.debug(AST);
                if(String.isNotBlank(AST)&&AST!='null'&&AST!=null){
                    string pfAST='';                
                    if (AST=='SH'){
                       pfAST = 'Ship to';
                    }
                    else if (AST=='BP'){
                       pfAST = 'Bill to';
                    }
                    else if (AST=='SP'){
                       pfAST = 'Sold to';
                    }
                    else{
                        pfAST=AST;
                    }
                    if(!setAST.contains(pfAST) && string.isNotBlank(pfAST)){                        
                        setAST.add(pfAST);
                    }
                }
            }			
            if(!setAST.isEmpty()){
                lstAST.clear();
            	lstAST.AddAll(setAST);
                system.debug(lstAST);
                if(setAST.contains('Sold to') && !setAST.contains('Ship to')){
                    lstAST.add('Ship to');
                }
                trgAccount.Account_Subtype__c = string.join(lstAST, ';');
            }
            
        }
    }
}