force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Account</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture project opportunities.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Standard</fullName>
            </value>
            <value>
                <fullName>DXV</fullName>
            </value>
            <value>
                <fullName>Grohe</fullName>
            </value>
            <value>
                <fullName>FIAT</fullName>
            </value>
            <value>
                <fullName>Crane</fullName>
            </value>
            <value>
                <fullName>Inax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Project address&#39; city</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&#39;US&#39;</defaultValue>
    <description>Project address&#39; country</description>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Project address&#39; zip/postal code</description>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Region__c.field-meta.xml
<CustomField>
    <fullName>Project_Region__c</fullName>
    <label>Project Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>MRO</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Northwest</fullName>
            </value>
            <value>
                <fullName>Southcentral</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
            <value>
                <fullName>Transfer DC Location</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Type of property on this project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDUCATION</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>GOVERNMENT/MILITARY</fullName>
                <label>Government/Military</label>
            </value>
            <value>
                <fullName>HEALTHCARE</fullName>
                <label>Healthcare</label>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
                <label>Hospitality</label>
            </value>
            <value>
                <fullName>MIXED USE DEV</fullName>
                <label>Mixed Use Dev</label>
            </value>
            <value>
                <fullName>MULTI FAMILY</fullName>
                <label>Multi Family</label>
            </value>
            <value>
                <fullName>OFFICE BUILDING</fullName>
                <label>Office Building</label>
            </value>
            <value>
                <fullName>PRISON</fullName>
                <label>Prison</label>
            </value>
            <value>
                <fullName>RELIGIOUS/CULTURAL FACILITIES</fullName>
                <label>Religious/Cultural Facilities</label>
            </value>
            <value>
                <fullName>RESTAURANT/RETAIL</fullName>
                <label>Restaurant/Retail</label>
            </value>
            <value>
                <fullName>SHIP</fullName>
                <label>Ship</label>
            </value>
            <value>
                <fullName>SINGLE FAMILY</fullName>
                <label>Single Family</label>
            </value>
            <value>
                <fullName>STADIUM/ENTERTAINMENT</fullName>
                <label>Stadium/Entertainment</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Airport</fullName>
            </value>
            <value>
                <fullName>Amusement Park</fullName>
                <isActive>false</isActive>
                <label>AMUSEMENT PARK</label>
            </value>
            <value>
                <fullName>Barracks/Army</fullName>
                <isActive>false</isActive>
                <label>BARRACKS/ARMY</label>
            </value>
            <value>
                <fullName>Buss/Comm Build/Comp</fullName>
                <isActive>false</isActive>
                <label>BUSS/COMM BUILD/COMP</label>
            </value>
            <value>
                <fullName>City/Public Sector</fullName>
                <isActive>false</isActive>
                <label>CITY/PUBLIC SECTOR</label>
            </value>
            <value>
                <fullName>Cultural Facilities</fullName>
                <isActive>false</isActive>
                <label>CULTURAL FACILITIES</label>
            </value>
            <value>
                <fullName>Dept Store/Shopping</fullName>
                <isActive>false</isActive>
                <label>DEPT STORE/SHOPPING</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>GOVERNMENT</label>
            </value>
            <value>
                <fullName>Government Building</fullName>
                <isActive>false</isActive>
                <label>GOVERNMENT BUILDING</label>
            </value>
            <value>
                <fullName>Green Buildings</fullName>
                <isActive>false</isActive>
                <label>GREEN BUILDINGS</label>
            </value>
            <value>
                <fullName>HOSPITAL/MEDICAL CARE</fullName>
                <isActive>false</isActive>
                <label>HOSPITAL/MEDICAL CARE</label>
            </value>
            <value>
                <fullName>Hospitals</fullName>
                <isActive>false</isActive>
                <label>HOSPITALS</label>
            </value>
            <value>
                <fullName>Hotel</fullName>
                <isActive>false</isActive>
                <label>HOTEL</label>
            </value>
            <value>
                <fullName>Hospital/Medical Car</fullName>
                <isActive>false</isActive>
                <label>Hospital/Medical Car</label>
            </value>
            <value>
                <fullName>Hotel / Motel</fullName>
                <isActive>false</isActive>
                <label>Hotel / Motel</label>
            </value>
            <value>
                <fullName>Hotel 4/5 Stars</fullName>
                <isActive>false</isActive>
                <label>Hotel 4/5 Stars</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Project address&#39; state</description>
    <label>State/Province</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <label>Project Team</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Teams</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wholesalers__c/Wholesalers__c.object-meta.xml
<CustomObject>
    <label>Wholesalers</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Wholesaler  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wholesalers__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Wholesalers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CheckBoxFolder_Controller_Test.cls
@IsTest
public class CheckBoxFolder_Controller_Test {
    @TestSetup static void createTestSetupData(){
        Id StdPriceBookId = UtilityTest.getStandardPBId();
        Project__c proj = UtilityTest.createProject();
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
            Project_Team__c projTeamMember1 = UtilityTest.createProjectTeam(proj.Id);            
            Account acc1 = UtilityTest.createCustomerAccount();            
            acc1.Brand__c = 'American Standard;Grohe;FIAT';
            update acc1;
            Wholesalers__c ws1 = UtilityTest.createWholesaler(acc1.Id, proj.Id);
            
            Opportunity OppProj = UtilityTest.createProjectOpportunity(proj.Id);            
            Quote quote1 = UtilityTest.createStandardQuote(StdPriceBookId, acc1.Id, OppProj);
            Product2 ASProd = UtilityTest.createAmericanStandardProduct(StdPriceBookId);
            QuoteLineItem qli1 = UtilityTest.createQLI(StdPriceBookId,quote1,ASProd);
            
            test.startTest();
            Order ord1 = UtilityTest.CreateOrder(acc1.Id,quote1.Id,StdPriceBookId);
            OrderItem orditem1 = UtilityTest.CreateOrderItem(quote1.Id,qli1.Id,ASProd.Id,ord1.Id);
            quote1.Unique_id__c = '0507525556';
            quote1.Num_Approvals__c = 0;
            quote1.Status = 'Processed';
            quote1.Review_Price__c = True;
            update quote1;
            
            test.stopTest();
        }
    }
    
    @isTest static void test_Box_FRUP()
    {
        test.startTest();
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
            Quote qot = [select Id, Num_Approvals__c,recordtypeid,Status,Integration_Process_In_Progress__c from Quote limit 1];        
            box__FRUP__c frup = createBoxFolder('Test Obj Name',qot.id);
            CheckBoxFolder_Controller.isBoxFolderExits(qot.id);
            CheckBoxFolder_Controller.checkQuote(qot.id);             
            qot.Integration_Process_In_Progress__c =true;
            update qot;
            CheckBoxFolder_Controller.checkQuote(qot.Id); 
        }
        
        test.stopTest();
    }
    
    public static box__FRUP__c createBoxFolder(String strObjectName, Id objId){
        box__FRUP__c frup = new box__FRUP__c();
        frup.box__Object_Name__c = strObjectName;
        frup.box__Folder_ID__c = '12345';
        frup.box__Record_ID__c  = objId;
        insert frup;
        return frup;
    }
    
    /*
    public static Account createAgencyAccount(){
        Account acct = new Account();
        acct.Name = 'Test Agency Account';
        acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency').getRecordTypeId();
        acct.Brand__c = 'American Standard;DXV';
        acct.Account_Subtype__c = 'Sold to; Shipt to';
        insert acct;
        return acct;
    }
    
    public static Project__c createProject(){        
        
        Project__c prj = new Project__c();
        prj.Name = 'Test Project';
        prj.Project_Type__c = 'Ship';
        prj.City__c = 'Atlanta';
        prj.State__c = 'GA';
        prj.Postal_Code__c = '30301';
        prj.Country__c = 'US';
        prj.Stage__c = 'Open';
        
        prj.Project_Region__c = 'Southeast';
        
        insert prj;
        return prj;
    }
    public static Opportunity createProjectOpportunity(Id projectId){
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opporutnity';
        opp.StageName = 'Initiation';
        opp.CloseDate = Date.today().AddMonths(1);
        opp.Project__c = projectId;
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Projects').getRecordTypeId();
        //opp.FinalQuote__c.
        insert opp;
        return opp;
    }
    
    public static Quote createQuote( Opportunity oppt)
    {
        Quote qot = new Quote();
        qot.Name = 'Test Quote';
        qot.OpportunityId =oppt.id;
        qot.Status = 'Draft';
        qot.RecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('Standard_Quote').getRecordTypeId();
        qot.ExpirationDate = Date.today().AddMonths(1);
        //qot.Account__c = acctId;
        //Id stdPriceBookId = Test.getStandardPricebookId();
        //qot.Pricebook2Id = spbId;
        insert qot;
        return qot;
    }
    */
}