force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Account</label>
</CustomObject>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rep Agencies</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>DXV</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Grohe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/Agency_Zip_Code_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a setup object which will be used to assign the agencies contact based on the zip codes</description>
    <label>Agency Zip Code Assignment</label>
    <nameField>
        <label>Agency Zip Code Assignment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies Zip Code Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Recalculate_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Assignment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be used to recalculate the agencies, and will update the record under the account.</description>
    <inlineHelpText>Check this box if recalculation required. 
NOTE: recalculation may take time to be completely processed due to volume of data.</inlineHelpText>
    <label>Recalculate Assignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This picklist will be used to show the Type of the zip code</description>
    <inlineHelpText>Type of ZipCode</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PO BOX</fullName>
            </value>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>UNIQUE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agency_Zip_Code_Assignment__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <description>This field will be used to store the zip code for the agency assginment</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Zip Codes</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AgencyZipCodeAssignmentTrgTest.cls
@IsTest
public class AgencyZipCodeAssignmentTrgTest 
{
    //Create Sample Data 
    @TestSetup static void createTestSetupData()
    {
        Agency__c agn1 = UtilityTest.CreateAgency();
        UtilityTest.CreateAgencyZipCodeAssignment();
        
    }
    
    // Test Method check Assignment Zip Code
    @isTest static void testcheckAssignmentZipCode()
    {
        List<Agency_Zip_Code_Assignment__c> LstAGZC = [Select Id,Name,Recalculate_Assignment__c,ZipCode__c from Agency_Zip_Code_Assignment__c limit 4];
        List<Agency__c> ListOfAgencies = [Select Id,Name,Type__c,Account__c from Agency__c limit 4];
        Set<Id> SetofAccounts = new Set<Id>();
        Integer i = 1;
        for(Agency__c agn: ListOfAgencies)
        {
            if(i==1) agn.Type__c = 'AS';
            else if(i==2) agn.Type__c = 'DXV';
            else if(i==3) agn.Type__c = 'Fiat';
            else if(i==4) agn.Type__c = 'Grohe';
            i++;
            SetofAccounts.add(agn.Account__c);
        }
        
        for(Agency_Zip_Code_Assignment__c agnZC : LstAGZC)
        {
            agnZC.Recalculate_Assignment__c = true;
        }
        List<Account> LstAccountObj = new List<Account>();
        if(SetofAccounts.size() > 0)
        {
            for(Account acc: [Select Id,Name,ShippingPostalCode from Account where Id in: SetofAccounts])
            {
                acc.ShippingPostalCode = '220065';
                LstAccountObj.add(acc);
            }
            Update LstAccountObj;
        }
        
        
        /* Account AccountObj = UtilityTest.CreateAccount('Test Account1', false);
AccountObj.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Influencer').getRecordTypeId();
AccountObj.ShippingPostalCode = 'TEST';

insert AccountObj; */
        
        Test.startTest();
        system.debug('LstAccountObj::'+LstAccountObj);
        system.debug('ListOfAgencies::'+ListOfAgencies);
        system.debug('LstAGZC::'+LstAGZC);
        Update ListOfAgencies;
        Update LstAGZC;
        Test.stopTest();
    }
}