force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Account</label>
</CustomObject>

force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Case Queue Assignment</label>
</CustomObject>

force-app/main/default/objects/Defect_Return_Form__c/Defect_Return_Form__c.object-meta.xml
<CustomObject>
    <label>Defect Return Line</label>
    <nameField>
        <label>Defect Return Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Defect Return Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Defect_Return_Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Defect_Return_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect_Return_Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Defect_Return</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipName>Defect_Return_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect_Return_Form__c/fields/Reference_Number_BP__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number_BP__c</fullName>
    <label>Reference Number (BP)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect_Return_Form__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Defect_Return_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/defectReturnBatchSchedule.cls
/************************
Author:         Hanif Babar
Created Date:   15/Aug/2018 
Purpose:        defectReturnBatchSchedule

************************MODIFICATION HISTORY**************************************
Added on             Added By               Description
**********************************************************************************
15/Aug/2018           Hanif Babar          Initial Development 
***********************************************************************************/
global class defectReturnBatchSchedule implements Database.Batchable<sObject>,Schedulable{
    private id caseRecordTypeId;
    private id queueid;
    global void execute(SchedulableContext sc)        
    {
        defectReturnBatchSchedule t = new defectReturnBatchSchedule();
        Database.executeBatch(t);  
    }
    global defectReturnBatchSchedule(){
        caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Defect_Return').getRecordTypeId();
        List<Group> queueidList  = [select Id, Name, DeveloperName from Group where Type = 'Queue' and DeveloperName='Grohe_Goods_Associate' LIMIT 1];        
        if(queueidList.size()>0)
        {
            queueid = queueidList[0].id;
        }
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        // Get all defect retrun lins whoes defect return case is not created
        string query =   'Select Id,Reference_Number_BP__c,Case__c,Account__c,Requested_By__c '+
                        'From Defect_Return_Form__c '+
                        'Where Case__c = null '+
                   		'and Account__c != null '+ 
                        'and Reference_Number_BP__c !=null order by Reference_Number_BP__c';
        system.debug(query);
        system.debug(Database.query(query));
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        // Prepare multil defect lines for a case entry
        List<AggregateResult> ar =[Select Reference_Number_BP__c, 
                                 	Account__c,
                                    Requested_By__c
                            From Defect_Return_Form__c
                            Where Id  in :scope
                            Group by Reference_Number_BP__c, Account__c, Requested_By__c order by Reference_Number_BP__c];
        
        map<string,Case> mapCase = new map<string,Case>();
        for(AggregateResult element:ar){
            Case aCase = new Case(RecordTypeId = caseRecordTypeId,                                  
                                  AccountId = (Id)element.get('Account__c'), 
                                  Defect_Return_Reference_Number__c = string.valueof(element.get('Reference_Number_BP__c')),
                                  Origin = 'Business Portal',
                                  status = 'Open',
                                  OwnerId = queueid);            
            if (string.isNotBlank(string.valueof(element.get('Requested_By__c')))){
                aCase.ContactId = (Id)element.get('Requested_By__c');
            }
            
            mapCase.put(string.valueof(element.get('Reference_Number_BP__c')), aCase);
        }
        system.debug(mapCase);
        Insert mapCase.values();
        List<Defect_Return_Form__c> lstDRF = (List<Defect_Return_Form__c>)scope;
        for(Defect_Return_Form__c element : lstDRF){
            if(mapCase.containsKey(element.Reference_Number_BP__c)){
                element.put('Case__c',mapCase.get(element.Reference_Number_BP__c).Id); 
            }            
        }
        update lstDRF;
    }
    
    global void finish(Database.BatchableContext BC){
    }
}